//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ElvisDataModel.EDMX
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ClusterWW_SafetySystemsModel : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ClusterWW_SafetySystemsModel object using the connection string found in the 'ClusterWW_SafetySystemsModel' section of the application configuration file.
        /// </summary>
        public ClusterWW_SafetySystemsModel() : base("name=ClusterWW_SafetySystemsModel", "ClusterWW_SafetySystemsModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClusterWW_SafetySystemsModel object.
        /// </summary>
        public ClusterWW_SafetySystemsModel(string connectionString) : base(connectionString, "ClusterWW_SafetySystemsModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ClusterWW_SafetySystemsModel object.
        /// </summary>
        public ClusterWW_SafetySystemsModel(EntityConnection connection) : base(connection, "ClusterWW_SafetySystemsModel")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SAS_NM_DataWithDateAndTimeJoinedForElvis> SAS_NM_DataWithDateAndTimeJoinedForElvis
        {
            get
            {
                if ((_SAS_NM_DataWithDateAndTimeJoinedForElvis == null))
                {
                    _SAS_NM_DataWithDateAndTimeJoinedForElvis = base.CreateObjectSet<SAS_NM_DataWithDateAndTimeJoinedForElvis>("SAS_NM_DataWithDateAndTimeJoinedForElvis");
                }
                return _SAS_NM_DataWithDateAndTimeJoinedForElvis;
            }
        }
        private ObjectSet<SAS_NM_DataWithDateAndTimeJoinedForElvis> _SAS_NM_DataWithDateAndTimeJoinedForElvis;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SAS_NM_Actions> SAS_NM_Actions
        {
            get
            {
                if ((_SAS_NM_Actions == null))
                {
                    _SAS_NM_Actions = base.CreateObjectSet<SAS_NM_Actions>("SAS_NM_Actions");
                }
                return _SAS_NM_Actions;
            }
        }
        private ObjectSet<SAS_NM_Actions> _SAS_NM_Actions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SAS_NM_DataForElvis> SAS_NM_DataForElvis
        {
            get
            {
                if ((_SAS_NM_DataForElvis == null))
                {
                    _SAS_NM_DataForElvis = base.CreateObjectSet<SAS_NM_DataForElvis>("SAS_NM_DataForElvis");
                }
                return _SAS_NM_DataForElvis;
            }
        }
        private ObjectSet<SAS_NM_DataForElvis> _SAS_NM_DataForElvis;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SAS_NM_DataWithDateAndTimeJoinedForElvis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSAS_NM_DataWithDateAndTimeJoinedForElvis(SAS_NM_DataWithDateAndTimeJoinedForElvis sAS_NM_DataWithDateAndTimeJoinedForElvis)
        {
            base.AddObject("SAS_NM_DataWithDateAndTimeJoinedForElvis", sAS_NM_DataWithDateAndTimeJoinedForElvis);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SAS_NM_Actions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSAS_NM_Actions(SAS_NM_Actions sAS_NM_Actions)
        {
            base.AddObject("SAS_NM_Actions", sAS_NM_Actions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SAS_NM_DataForElvis EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSAS_NM_DataForElvis(SAS_NM_DataForElvis sAS_NM_DataForElvis)
        {
            base.AddObject("SAS_NM_DataForElvis", sAS_NM_DataForElvis);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WW_SafetySystemsModel", Name="SAS_NM_Actions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SAS_NM_Actions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SAS_NM_Actions object.
        /// </summary>
        /// <param name="aCTION_INDEX">Initial value of the ACTION_INDEX property.</param>
        public static SAS_NM_Actions CreateSAS_NM_Actions(global::System.Int32 aCTION_INDEX)
        {
            SAS_NM_Actions sAS_NM_Actions = new SAS_NM_Actions();
            sAS_NM_Actions.ACTION_INDEX = aCTION_INDEX;
            return sAS_NM_Actions;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ACTION_INDEX
        {
            get
            {
                return _ACTION_INDEX;
            }
            set
            {
                if (_ACTION_INDEX != value)
                {
                    OnACTION_INDEXChanging(value);
                    ReportPropertyChanging("ACTION_INDEX");
                    _ACTION_INDEX = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ACTION_INDEX");
                    OnACTION_INDEXChanged();
                }
            }
        }
        private global::System.Int32 _ACTION_INDEX;
        partial void OnACTION_INDEXChanging(global::System.Int32 value);
        partial void OnACTION_INDEXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NM_INDEX
        {
            get
            {
                return _NM_INDEX;
            }
            set
            {
                OnNM_INDEXChanging(value);
                ReportPropertyChanging("NM_INDEX");
                _NM_INDEX = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NM_INDEX");
                OnNM_INDEXChanged();
            }
        }
        private Nullable<global::System.Int32> _NM_INDEX;
        partial void OnNM_INDEXChanging(Nullable<global::System.Int32> value);
        partial void OnNM_INDEXChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACTION
        {
            get
            {
                return _ACTION;
            }
            set
            {
                OnACTIONChanging(value);
                ReportPropertyChanging("ACTION");
                _ACTION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACTION");
                OnACTIONChanged();
            }
        }
        private global::System.String _ACTION;
        partial void OnACTIONChanging(global::System.String value);
        partial void OnACTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACTION_OWNER
        {
            get
            {
                return _ACTION_OWNER;
            }
            set
            {
                OnACTION_OWNERChanging(value);
                ReportPropertyChanging("ACTION_OWNER");
                _ACTION_OWNER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACTION_OWNER");
                OnACTION_OWNERChanged();
            }
        }
        private global::System.String _ACTION_OWNER;
        partial void OnACTION_OWNERChanging(global::System.String value);
        partial void OnACTION_OWNERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ACTION_STATUS
        {
            get
            {
                return _ACTION_STATUS;
            }
            set
            {
                OnACTION_STATUSChanging(value);
                ReportPropertyChanging("ACTION_STATUS");
                _ACTION_STATUS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ACTION_STATUS");
                OnACTION_STATUSChanged();
            }
        }
        private Nullable<global::System.Int32> _ACTION_STATUS;
        partial void OnACTION_STATUSChanging(Nullable<global::System.Int32> value);
        partial void OnACTION_STATUSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ACTION_COMPLETE
        {
            get
            {
                return _ACTION_COMPLETE;
            }
            set
            {
                OnACTION_COMPLETEChanging(value);
                ReportPropertyChanging("ACTION_COMPLETE");
                _ACTION_COMPLETE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ACTION_COMPLETE");
                OnACTION_COMPLETEChanged();
            }
        }
        private Nullable<global::System.DateTime> _ACTION_COMPLETE;
        partial void OnACTION_COMPLETEChanging(Nullable<global::System.DateTime> value);
        partial void OnACTION_COMPLETEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ACTION_TARGET
        {
            get
            {
                return _ACTION_TARGET;
            }
            set
            {
                OnACTION_TARGETChanging(value);
                ReportPropertyChanging("ACTION_TARGET");
                _ACTION_TARGET = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ACTION_TARGET");
                OnACTION_TARGETChanged();
            }
        }
        private Nullable<global::System.DateTime> _ACTION_TARGET;
        partial void OnACTION_TARGETChanging(Nullable<global::System.DateTime> value);
        partial void OnACTION_TARGETChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACTION_NOTIFICATION
        {
            get
            {
                return _ACTION_NOTIFICATION;
            }
            set
            {
                OnACTION_NOTIFICATIONChanging(value);
                ReportPropertyChanging("ACTION_NOTIFICATION");
                _ACTION_NOTIFICATION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ACTION_NOTIFICATION");
                OnACTION_NOTIFICATIONChanged();
            }
        }
        private global::System.String _ACTION_NOTIFICATION;
        partial void OnACTION_NOTIFICATIONChanging(global::System.String value);
        partial void OnACTION_NOTIFICATIONChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WW_SafetySystemsModel", Name="SAS_NM_DataForElvis")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SAS_NM_DataForElvis : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SAS_NM_DataForElvis object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="managerSeverityCatagory">Initial value of the managerSeverityCatagory property.</param>
        /// <param name="managerPriority">Initial value of the managerPriority property.</param>
        /// <param name="managerContained">Initial value of the managerContained property.</param>
        /// <param name="ownerPersonToldOfRecomendation">Initial value of the ownerPersonToldOfRecomendation property.</param>
        /// <param name="ownerPriority">Initial value of the ownerPriority property.</param>
        public static SAS_NM_DataForElvis CreateSAS_NM_DataForElvis(global::System.Int32 id, global::System.String managerSeverityCatagory, global::System.String managerPriority, global::System.String managerContained, global::System.String ownerPersonToldOfRecomendation, global::System.String ownerPriority)
        {
            SAS_NM_DataForElvis sAS_NM_DataForElvis = new SAS_NM_DataForElvis();
            sAS_NM_DataForElvis.ID = id;
            sAS_NM_DataForElvis.managerSeverityCatagory = managerSeverityCatagory;
            sAS_NM_DataForElvis.managerPriority = managerPriority;
            sAS_NM_DataForElvis.managerContained = managerContained;
            sAS_NM_DataForElvis.ownerPersonToldOfRecomendation = ownerPersonToldOfRecomendation;
            sAS_NM_DataForElvis.ownerPriority = ownerPriority;
            return sAS_NM_DataForElvis;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String initiatorName
        {
            get
            {
                return _initiatorName;
            }
            set
            {
                OninitiatorNameChanging(value);
                ReportPropertyChanging("initiatorName");
                _initiatorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("initiatorName");
                OninitiatorNameChanged();
            }
        }
        private global::System.String _initiatorName;
        partial void OninitiatorNameChanging(global::System.String value);
        partial void OninitiatorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String initiatorTrioAllocation
        {
            get
            {
                return _initiatorTrioAllocation;
            }
            set
            {
                OninitiatorTrioAllocationChanging(value);
                ReportPropertyChanging("initiatorTrioAllocation");
                _initiatorTrioAllocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("initiatorTrioAllocation");
                OninitiatorTrioAllocationChanged();
            }
        }
        private global::System.String _initiatorTrioAllocation;
        partial void OninitiatorTrioAllocationChanging(global::System.String value);
        partial void OninitiatorTrioAllocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String initiatorLocation
        {
            get
            {
                return _initiatorLocation;
            }
            set
            {
                OninitiatorLocationChanging(value);
                ReportPropertyChanging("initiatorLocation");
                _initiatorLocation = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("initiatorLocation");
                OninitiatorLocationChanged();
            }
        }
        private global::System.String _initiatorLocation;
        partial void OninitiatorLocationChanging(global::System.String value);
        partial void OninitiatorLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String initiatorType
        {
            get
            {
                return _initiatorType;
            }
            set
            {
                OninitiatorTypeChanging(value);
                ReportPropertyChanging("initiatorType");
                _initiatorType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("initiatorType");
                OninitiatorTypeChanged();
            }
        }
        private global::System.String _initiatorType;
        partial void OninitiatorTypeChanging(global::System.String value);
        partial void OninitiatorTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String initiatorEmployerAndRota
        {
            get
            {
                return _initiatorEmployerAndRota;
            }
            set
            {
                OninitiatorEmployerAndRotaChanging(value);
                ReportPropertyChanging("initiatorEmployerAndRota");
                _initiatorEmployerAndRota = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("initiatorEmployerAndRota");
                OninitiatorEmployerAndRotaChanged();
            }
        }
        private global::System.String _initiatorEmployerAndRota;
        partial void OninitiatorEmployerAndRotaChanging(global::System.String value);
        partial void OninitiatorEmployerAndRotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> initiatorDateAndTime
        {
            get
            {
                return _initiatorDateAndTime;
            }
            set
            {
                OninitiatorDateAndTimeChanging(value);
                ReportPropertyChanging("initiatorDateAndTime");
                _initiatorDateAndTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("initiatorDateAndTime");
                OninitiatorDateAndTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _initiatorDateAndTime;
        partial void OninitiatorDateAndTimeChanging(Nullable<global::System.DateTime> value);
        partial void OninitiatorDateAndTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String initiatorReportType
        {
            get
            {
                return _initiatorReportType;
            }
            set
            {
                OninitiatorReportTypeChanging(value);
                ReportPropertyChanging("initiatorReportType");
                _initiatorReportType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("initiatorReportType");
                OninitiatorReportTypeChanged();
            }
        }
        private global::System.String _initiatorReportType;
        partial void OninitiatorReportTypeChanging(global::System.String value);
        partial void OninitiatorReportTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String initiatorSapNotification
        {
            get
            {
                return _initiatorSapNotification;
            }
            set
            {
                OninitiatorSapNotificationChanging(value);
                ReportPropertyChanging("initiatorSapNotification");
                _initiatorSapNotification = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("initiatorSapNotification");
                OninitiatorSapNotificationChanged();
            }
        }
        private global::System.String _initiatorSapNotification;
        partial void OninitiatorSapNotificationChanging(global::System.String value);
        partial void OninitiatorSapNotificationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String initiatorDescriptionOfIncident
        {
            get
            {
                return _initiatorDescriptionOfIncident;
            }
            set
            {
                OninitiatorDescriptionOfIncidentChanging(value);
                ReportPropertyChanging("initiatorDescriptionOfIncident");
                _initiatorDescriptionOfIncident = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("initiatorDescriptionOfIncident");
                OninitiatorDescriptionOfIncidentChanged();
            }
        }
        private global::System.String _initiatorDescriptionOfIncident;
        partial void OninitiatorDescriptionOfIncidentChanging(global::System.String value);
        partial void OninitiatorDescriptionOfIncidentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String managerName
        {
            get
            {
                return _managerName;
            }
            set
            {
                OnmanagerNameChanging(value);
                ReportPropertyChanging("managerName");
                _managerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("managerName");
                OnmanagerNameChanged();
            }
        }
        private global::System.String _managerName;
        partial void OnmanagerNameChanging(global::System.String value);
        partial void OnmanagerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String managerSiteInspected
        {
            get
            {
                return _managerSiteInspected;
            }
            set
            {
                OnmanagerSiteInspectedChanging(value);
                ReportPropertyChanging("managerSiteInspected");
                _managerSiteInspected = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("managerSiteInspected");
                OnmanagerSiteInspectedChanged();
            }
        }
        private global::System.String _managerSiteInspected;
        partial void OnmanagerSiteInspectedChanging(global::System.String value);
        partial void OnmanagerSiteInspectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String managerSeverityCatagory
        {
            get
            {
                return _managerSeverityCatagory;
            }
            set
            {
                if (_managerSeverityCatagory != value)
                {
                    OnmanagerSeverityCatagoryChanging(value);
                    ReportPropertyChanging("managerSeverityCatagory");
                    _managerSeverityCatagory = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("managerSeverityCatagory");
                    OnmanagerSeverityCatagoryChanged();
                }
            }
        }
        private global::System.String _managerSeverityCatagory;
        partial void OnmanagerSeverityCatagoryChanging(global::System.String value);
        partial void OnmanagerSeverityCatagoryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String managerPriority
        {
            get
            {
                return _managerPriority;
            }
            set
            {
                if (_managerPriority != value)
                {
                    OnmanagerPriorityChanging(value);
                    ReportPropertyChanging("managerPriority");
                    _managerPriority = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("managerPriority");
                    OnmanagerPriorityChanged();
                }
            }
        }
        private global::System.String _managerPriority;
        partial void OnmanagerPriorityChanging(global::System.String value);
        partial void OnmanagerPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String managerContained
        {
            get
            {
                return _managerContained;
            }
            set
            {
                if (_managerContained != value)
                {
                    OnmanagerContainedChanging(value);
                    ReportPropertyChanging("managerContained");
                    _managerContained = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("managerContained");
                    OnmanagerContainedChanged();
                }
            }
        }
        private global::System.String _managerContained;
        partial void OnmanagerContainedChanging(global::System.String value);
        partial void OnmanagerContainedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String managerInitialActionTaken
        {
            get
            {
                return _managerInitialActionTaken;
            }
            set
            {
                OnmanagerInitialActionTakenChanging(value);
                ReportPropertyChanging("managerInitialActionTaken");
                _managerInitialActionTaken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("managerInitialActionTaken");
                OnmanagerInitialActionTakenChanged();
            }
        }
        private global::System.String _managerInitialActionTaken;
        partial void OnmanagerInitialActionTakenChanging(global::System.String value);
        partial void OnmanagerInitialActionTakenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String managerComments
        {
            get
            {
                return _managerComments;
            }
            set
            {
                OnmanagerCommentsChanging(value);
                ReportPropertyChanging("managerComments");
                _managerComments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("managerComments");
                OnmanagerCommentsChanged();
            }
        }
        private global::System.String _managerComments;
        partial void OnmanagerCommentsChanging(global::System.String value);
        partial void OnmanagerCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String repName
        {
            get
            {
                return _repName;
            }
            set
            {
                OnrepNameChanging(value);
                ReportPropertyChanging("repName");
                _repName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("repName");
                OnrepNameChanged();
            }
        }
        private global::System.String _repName;
        partial void OnrepNameChanging(global::System.String value);
        partial void OnrepNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String repComments
        {
            get
            {
                return _repComments;
            }
            set
            {
                OnrepCommentsChanging(value);
                ReportPropertyChanging("repComments");
                _repComments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("repComments");
                OnrepCommentsChanged();
            }
        }
        private global::System.String _repComments;
        partial void OnrepCommentsChanging(global::System.String value);
        partial void OnrepCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ownerName
        {
            get
            {
                return _ownerName;
            }
            set
            {
                OnownerNameChanging(value);
                ReportPropertyChanging("ownerName");
                _ownerName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ownerName");
                OnownerNameChanged();
            }
        }
        private global::System.String _ownerName;
        partial void OnownerNameChanging(global::System.String value);
        partial void OnownerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ownerPersonToldOfRecomendation
        {
            get
            {
                return _ownerPersonToldOfRecomendation;
            }
            set
            {
                if (_ownerPersonToldOfRecomendation != value)
                {
                    OnownerPersonToldOfRecomendationChanging(value);
                    ReportPropertyChanging("ownerPersonToldOfRecomendation");
                    _ownerPersonToldOfRecomendation = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ownerPersonToldOfRecomendation");
                    OnownerPersonToldOfRecomendationChanged();
                }
            }
        }
        private global::System.String _ownerPersonToldOfRecomendation;
        partial void OnownerPersonToldOfRecomendationChanging(global::System.String value);
        partial void OnownerPersonToldOfRecomendationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ownerPriority
        {
            get
            {
                return _ownerPriority;
            }
            set
            {
                if (_ownerPriority != value)
                {
                    OnownerPriorityChanging(value);
                    ReportPropertyChanging("ownerPriority");
                    _ownerPriority = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ownerPriority");
                    OnownerPriorityChanged();
                }
            }
        }
        private global::System.String _ownerPriority;
        partial void OnownerPriorityChanging(global::System.String value);
        partial void OnownerPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ownerSectionManagersComments
        {
            get
            {
                return _ownerSectionManagersComments;
            }
            set
            {
                OnownerSectionManagersCommentsChanging(value);
                ReportPropertyChanging("ownerSectionManagersComments");
                _ownerSectionManagersComments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ownerSectionManagersComments");
                OnownerSectionManagersCommentsChanged();
            }
        }
        private global::System.String _ownerSectionManagersComments;
        partial void OnownerSectionManagersCommentsChanging(global::System.String value);
        partial void OnownerSectionManagersCommentsChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="WW_SafetySystemsModel", Name="SAS_NM_DataWithDateAndTimeJoinedForElvis")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SAS_NM_DataWithDateAndTimeJoinedForElvis : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SAS_NM_DataWithDateAndTimeJoinedForElvis object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="possibleInjury">Initial value of the PossibleInjury property.</param>
        /// <param name="damageToPlant">Initial value of the DamageToPlant property.</param>
        /// <param name="siteInspected">Initial value of the SiteInspected property.</param>
        /// <param name="personToldOfRecommendation">Initial value of the PersonToldOfRecommendation property.</param>
        /// <param name="contained">Initial value of the Contained property.</param>
        public static SAS_NM_DataWithDateAndTimeJoinedForElvis CreateSAS_NM_DataWithDateAndTimeJoinedForElvis(global::System.Int32 id, global::System.Boolean possibleInjury, global::System.Boolean damageToPlant, global::System.Boolean siteInspected, global::System.Boolean personToldOfRecommendation, global::System.Boolean contained)
        {
            SAS_NM_DataWithDateAndTimeJoinedForElvis sAS_NM_DataWithDateAndTimeJoinedForElvis = new SAS_NM_DataWithDateAndTimeJoinedForElvis();
            sAS_NM_DataWithDateAndTimeJoinedForElvis.ID = id;
            sAS_NM_DataWithDateAndTimeJoinedForElvis.PossibleInjury = possibleInjury;
            sAS_NM_DataWithDateAndTimeJoinedForElvis.DamageToPlant = damageToPlant;
            sAS_NM_DataWithDateAndTimeJoinedForElvis.SiteInspected = siteInspected;
            sAS_NM_DataWithDateAndTimeJoinedForElvis.PersonToldOfRecommendation = personToldOfRecommendation;
            sAS_NM_DataWithDateAndTimeJoinedForElvis.Contained = contained;
            return sAS_NM_DataWithDateAndTimeJoinedForElvis;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InitiatorsName
        {
            get
            {
                return _InitiatorsName;
            }
            set
            {
                OnInitiatorsNameChanging(value);
                ReportPropertyChanging("InitiatorsName");
                _InitiatorsName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InitiatorsName");
                OnInitiatorsNameChanged();
            }
        }
        private global::System.String _InitiatorsName;
        partial void OnInitiatorsNameChanging(global::System.String value);
        partial void OnInitiatorsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DescriptionOfAccident
        {
            get
            {
                return _DescriptionOfAccident;
            }
            set
            {
                OnDescriptionOfAccidentChanging(value);
                ReportPropertyChanging("DescriptionOfAccident");
                _DescriptionOfAccident = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DescriptionOfAccident");
                OnDescriptionOfAccidentChanged();
            }
        }
        private global::System.String _DescriptionOfAccident;
        partial void OnDescriptionOfAccidentChanging(global::System.String value);
        partial void OnDescriptionOfAccidentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PossibleInjury
        {
            get
            {
                return _PossibleInjury;
            }
            set
            {
                if (_PossibleInjury != value)
                {
                    OnPossibleInjuryChanging(value);
                    ReportPropertyChanging("PossibleInjury");
                    _PossibleInjury = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PossibleInjury");
                    OnPossibleInjuryChanged();
                }
            }
        }
        private global::System.Boolean _PossibleInjury;
        partial void OnPossibleInjuryChanging(global::System.Boolean value);
        partial void OnPossibleInjuryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean DamageToPlant
        {
            get
            {
                return _DamageToPlant;
            }
            set
            {
                if (_DamageToPlant != value)
                {
                    OnDamageToPlantChanging(value);
                    ReportPropertyChanging("DamageToPlant");
                    _DamageToPlant = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DamageToPlant");
                    OnDamageToPlantChanged();
                }
            }
        }
        private global::System.Boolean _DamageToPlant;
        partial void OnDamageToPlantChanging(global::System.Boolean value);
        partial void OnDamageToPlantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeInspected
        {
            get
            {
                return _TimeInspected;
            }
            set
            {
                OnTimeInspectedChanging(value);
                ReportPropertyChanging("TimeInspected");
                _TimeInspected = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeInspected");
                OnTimeInspectedChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeInspected;
        partial void OnTimeInspectedChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeInspectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean SiteInspected
        {
            get
            {
                return _SiteInspected;
            }
            set
            {
                if (_SiteInspected != value)
                {
                    OnSiteInspectedChanging(value);
                    ReportPropertyChanging("SiteInspected");
                    _SiteInspected = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SiteInspected");
                    OnSiteInspectedChanged();
                }
            }
        }
        private global::System.Boolean _SiteInspected;
        partial void OnSiteInspectedChanging(global::System.Boolean value);
        partial void OnSiteInspectedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comments
        {
            get
            {
                return _Comments;
            }
            set
            {
                OnCommentsChanging(value);
                ReportPropertyChanging("Comments");
                _Comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comments");
                OnCommentsChanged();
            }
        }
        private global::System.String _Comments;
        partial void OnCommentsChanging(global::System.String value);
        partial void OnCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InitialActionTaken
        {
            get
            {
                return _InitialActionTaken;
            }
            set
            {
                OnInitialActionTakenChanging(value);
                ReportPropertyChanging("InitialActionTaken");
                _InitialActionTaken = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InitialActionTaken");
                OnInitialActionTakenChanged();
            }
        }
        private global::System.String _InitialActionTaken;
        partial void OnInitialActionTakenChanging(global::System.String value);
        partial void OnInitialActionTakenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SupervisorsName
        {
            get
            {
                return _SupervisorsName;
            }
            set
            {
                OnSupervisorsNameChanging(value);
                ReportPropertyChanging("SupervisorsName");
                _SupervisorsName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SupervisorsName");
                OnSupervisorsNameChanged();
            }
        }
        private global::System.String _SupervisorsName;
        partial void OnSupervisorsNameChanging(global::System.String value);
        partial void OnSupervisorsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SafetyRepsComments
        {
            get
            {
                return _SafetyRepsComments;
            }
            set
            {
                OnSafetyRepsCommentsChanging(value);
                ReportPropertyChanging("SafetyRepsComments");
                _SafetyRepsComments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SafetyRepsComments");
                OnSafetyRepsCommentsChanged();
            }
        }
        private global::System.String _SafetyRepsComments;
        partial void OnSafetyRepsCommentsChanging(global::System.String value);
        partial void OnSafetyRepsCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SafetyRepsName
        {
            get
            {
                return _SafetyRepsName;
            }
            set
            {
                OnSafetyRepsNameChanging(value);
                ReportPropertyChanging("SafetyRepsName");
                _SafetyRepsName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SafetyRepsName");
                OnSafetyRepsNameChanged();
            }
        }
        private global::System.String _SafetyRepsName;
        partial void OnSafetyRepsNameChanging(global::System.String value);
        partial void OnSafetyRepsNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SectionManagersComments
        {
            get
            {
                return _SectionManagersComments;
            }
            set
            {
                OnSectionManagersCommentsChanging(value);
                ReportPropertyChanging("SectionManagersComments");
                _SectionManagersComments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SectionManagersComments");
                OnSectionManagersCommentsChanged();
            }
        }
        private global::System.String _SectionManagersComments;
        partial void OnSectionManagersCommentsChanging(global::System.String value);
        partial void OnSectionManagersCommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private Nullable<global::System.Byte> _status;
        partial void OnstatusChanging(Nullable<global::System.Byte> value);
        partial void OnstatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean PersonToldOfRecommendation
        {
            get
            {
                return _PersonToldOfRecommendation;
            }
            set
            {
                if (_PersonToldOfRecommendation != value)
                {
                    OnPersonToldOfRecommendationChanging(value);
                    ReportPropertyChanging("PersonToldOfRecommendation");
                    _PersonToldOfRecommendation = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PersonToldOfRecommendation");
                    OnPersonToldOfRecommendationChanged();
                }
            }
        }
        private global::System.Boolean _PersonToldOfRecommendation;
        partial void OnPersonToldOfRecommendationChanging(global::System.Boolean value);
        partial void OnPersonToldOfRecommendationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Employer
        {
            get
            {
                return _Employer;
            }
            set
            {
                OnEmployerChanging(value);
                ReportPropertyChanging("Employer");
                _Employer = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Employer");
                OnEmployerChanged();
            }
        }
        private global::System.String _Employer;
        partial void OnEmployerChanging(global::System.String value);
        partial void OnEmployerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String works_area
        {
            get
            {
                return _works_area;
            }
            set
            {
                Onworks_areaChanging(value);
                ReportPropertyChanging("works_area");
                _works_area = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("works_area");
                Onworks_areaChanged();
            }
        }
        private global::System.String _works_area;
        partial void Onworks_areaChanging(global::System.String value);
        partial void Onworks_areaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sectionmanagersname
        {
            get
            {
                return _sectionmanagersname;
            }
            set
            {
                OnsectionmanagersnameChanging(value);
                ReportPropertyChanging("sectionmanagersname");
                _sectionmanagersname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sectionmanagersname");
                OnsectionmanagersnameChanged();
            }
        }
        private global::System.String _sectionmanagersname;
        partial void OnsectionmanagersnameChanging(global::System.String value);
        partial void OnsectionmanagersnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SEVERITY
        {
            get
            {
                return _SEVERITY;
            }
            set
            {
                OnSEVERITYChanging(value);
                ReportPropertyChanging("SEVERITY");
                _SEVERITY = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SEVERITY");
                OnSEVERITYChanged();
            }
        }
        private Nullable<global::System.Int32> _SEVERITY;
        partial void OnSEVERITYChanging(Nullable<global::System.Int32> value);
        partial void OnSEVERITYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> closure_date
        {
            get
            {
                return _closure_date;
            }
            set
            {
                Onclosure_dateChanging(value);
                ReportPropertyChanging("closure_date");
                _closure_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("closure_date");
                Onclosure_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _closure_date;
        partial void Onclosure_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onclosure_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OWNER
        {
            get
            {
                return _OWNER;
            }
            set
            {
                OnOWNERChanging(value);
                ReportPropertyChanging("OWNER");
                _OWNER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OWNER");
                OnOWNERChanged();
            }
        }
        private global::System.String _OWNER;
        partial void OnOWNERChanging(global::System.String value);
        partial void OnOWNERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ROTA
        {
            get
            {
                return _ROTA;
            }
            set
            {
                OnROTAChanging(value);
                ReportPropertyChanging("ROTA");
                _ROTA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ROTA");
                OnROTAChanged();
            }
        }
        private global::System.String _ROTA;
        partial void OnROTAChanging(global::System.String value);
        partial void OnROTAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> works_area_id
        {
            get
            {
                return _works_area_id;
            }
            set
            {
                Onworks_area_idChanging(value);
                ReportPropertyChanging("works_area_id");
                _works_area_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("works_area_id");
                Onworks_area_idChanged();
            }
        }
        private Nullable<global::System.Int32> _works_area_id;
        partial void Onworks_area_idChanging(Nullable<global::System.Int32> value);
        partial void Onworks_area_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Closed_by_name
        {
            get
            {
                return _Closed_by_name;
            }
            set
            {
                OnClosed_by_nameChanging(value);
                ReportPropertyChanging("Closed_by_name");
                _Closed_by_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Closed_by_name");
                OnClosed_by_nameChanged();
            }
        }
        private global::System.String _Closed_by_name;
        partial void OnClosed_by_nameChanging(global::System.String value);
        partial void OnClosed_by_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> Priority
        {
            get
            {
                return _Priority;
            }
            set
            {
                OnPriorityChanging(value);
                ReportPropertyChanging("Priority");
                _Priority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Priority");
                OnPriorityChanged();
            }
        }
        private Nullable<global::System.Byte> _Priority;
        partial void OnPriorityChanging(Nullable<global::System.Byte> value);
        partial void OnPriorityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Closed_by_id
        {
            get
            {
                return _Closed_by_id;
            }
            set
            {
                OnClosed_by_idChanging(value);
                ReportPropertyChanging("Closed_by_id");
                _Closed_by_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Closed_by_id");
                OnClosed_by_idChanged();
            }
        }
        private global::System.String _Closed_by_id;
        partial void OnClosed_by_idChanging(global::System.String value);
        partial void OnClosed_by_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nearmiss_type
        {
            get
            {
                return _Nearmiss_type;
            }
            set
            {
                OnNearmiss_typeChanging(value);
                ReportPropertyChanging("Nearmiss_type");
                _Nearmiss_type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Nearmiss_type");
                OnNearmiss_typeChanged();
            }
        }
        private global::System.String _Nearmiss_type;
        partial void OnNearmiss_typeChanging(global::System.String value);
        partial void OnNearmiss_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> report_type
        {
            get
            {
                return _report_type;
            }
            set
            {
                Onreport_typeChanging(value);
                ReportPropertyChanging("report_type");
                _report_type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("report_type");
                Onreport_typeChanged();
            }
        }
        private Nullable<global::System.Int32> _report_type;
        partial void Onreport_typeChanging(Nullable<global::System.Int32> value);
        partial void Onreport_typeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Contained
        {
            get
            {
                return _Contained;
            }
            set
            {
                if (_Contained != value)
                {
                    OnContainedChanging(value);
                    ReportPropertyChanging("Contained");
                    _Contained = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Contained");
                    OnContainedChanged();
                }
            }
        }
        private global::System.Boolean _Contained;
        partial void OnContainedChanging(global::System.Boolean value);
        partial void OnContainedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoteYesNo
        {
            get
            {
                return _NoteYesNo;
            }
            set
            {
                OnNoteYesNoChanging(value);
                ReportPropertyChanging("NoteYesNo");
                _NoteYesNo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoteYesNo");
                OnNoteYesNoChanged();
            }
        }
        private global::System.String _NoteYesNo;
        partial void OnNoteYesNoChanging(global::System.String value);
        partial void OnNoteYesNoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NoteNumber
        {
            get
            {
                return _NoteNumber;
            }
            set
            {
                OnNoteNumberChanging(value);
                ReportPropertyChanging("NoteNumber");
                _NoteNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NoteNumber");
                OnNoteNumberChanged();
            }
        }
        private global::System.String _NoteNumber;
        partial void OnNoteNumberChanging(global::System.String value);
        partial void OnNoteNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> MPriority
        {
            get
            {
                return _MPriority;
            }
            set
            {
                OnMPriorityChanging(value);
                ReportPropertyChanging("MPriority");
                _MPriority = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MPriority");
                OnMPriorityChanged();
            }
        }
        private Nullable<global::System.Byte> _MPriority;
        partial void OnMPriorityChanging(Nullable<global::System.Byte> value);
        partial void OnMPriorityChanged();

        #endregion

    
    }

    #endregion

    
}
