//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ElvisDataModel.EDMX
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class UnitSchemaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new UnitSchemaEntities object using the connection string found in the 'UnitSchemaEntities' section of the application configuration file.
        /// </summary>
        public UnitSchemaEntities() : base("name=UnitSchemaEntities", "UnitSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UnitSchemaEntities object.
        /// </summary>
        public UnitSchemaEntities(string connectionString) : base(connectionString, "UnitSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new UnitSchemaEntities object.
        /// </summary>
        public UnitSchemaEntities(EntityConnection connection) : base(connection, "UnitSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Caster> Casters
        {
            get
            {
                if ((_Casters == null))
                {
                    _Casters = base.CreateObjectSet<Caster>("Casters");
                }
                return _Casters;
            }
        }
        private ObjectSet<Caster> _Casters;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HMDesulph> HMDesulphs
        {
            get
            {
                if ((_HMDesulphs == null))
                {
                    _HMDesulphs = base.CreateObjectSet<HMDesulph>("HMDesulphs");
                }
                return _HMDesulphs;
            }
        }
        private ObjectSet<HMDesulph> _HMDesulphs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HMDesulphReport> HMDesulphReports
        {
            get
            {
                if ((_HMDesulphReports == null))
                {
                    _HMDesulphReports = base.CreateObjectSet<HMDesulphReport>("HMDesulphReports");
                }
                return _HMDesulphReports;
            }
        }
        private ObjectSet<HMDesulphReport> _HMDesulphReports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HMPour> HMPours
        {
            get
            {
                if ((_HMPours == null))
                {
                    _HMPours = base.CreateObjectSet<HMPour>("HMPours");
                }
                return _HMPours;
            }
        }
        private ObjectSet<HMPour> _HMPours;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SecSteel> SecSteels
        {
            get
            {
                if ((_SecSteels == null))
                {
                    _SecSteels = base.CreateObjectSet<SecSteel>("SecSteels");
                }
                return _SecSteels;
            }
        }
        private ObjectSet<SecSteel> _SecSteels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Vessel> Vessels
        {
            get
            {
                if ((_Vessels == null))
                {
                    _Vessels = base.CreateObjectSet<Vessel>("Vessels");
                }
                return _Vessels;
            }
        }
        private ObjectSet<Vessel> _Vessels;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Casters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCasters(Caster caster)
        {
            base.AddObject("Casters", caster);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HMDesulphs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHMDesulphs(HMDesulph hMDesulph)
        {
            base.AddObject("HMDesulphs", hMDesulph);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HMDesulphReports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHMDesulphReports(HMDesulphReport hMDesulphReport)
        {
            base.AddObject("HMDesulphReports", hMDesulphReport);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HMPours EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHMPours(HMPour hMPour)
        {
            base.AddObject("HMPours", hMPour);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SecSteels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSecSteels(SecSteel secSteel)
        {
            base.AddObject("SecSteels", secSteel);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Vessels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVessels(Vessel vessel)
        {
            base.AddObject("Vessels", vessel);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UnitSchema", Name="Caster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Caster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Caster object.
        /// </summary>
        /// <param name="casterIndex">Initial value of the CasterIndex property.</param>
        /// <param name="heatNumber">Initial value of the HeatNumber property.</param>
        /// <param name="hNS">Initial value of the HNS property.</param>
        public static Caster CreateCaster(global::System.Int32 casterIndex, global::System.Int32 heatNumber, global::System.Int32 hNS)
        {
            Caster caster = new Caster();
            caster.CasterIndex = casterIndex;
            caster.HeatNumber = heatNumber;
            caster.HNS = hNS;
            return caster;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CasterIndex
        {
            get
            {
                return _CasterIndex;
            }
            set
            {
                if (_CasterIndex != value)
                {
                    OnCasterIndexChanging(value);
                    ReportPropertyChanging("CasterIndex");
                    _CasterIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CasterIndex");
                    OnCasterIndexChanged();
                }
            }
        }
        private global::System.Int32 _CasterIndex;
        partial void OnCasterIndexChanging(global::System.Int32 value);
        partial void OnCasterIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                if (_HeatNumber != value)
                {
                    OnHeatNumberChanging(value);
                    ReportPropertyChanging("HeatNumber");
                    _HeatNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HeatNumber");
                    OnHeatNumberChanged();
                }
            }
        }
        private global::System.Int32 _HeatNumber;
        partial void OnHeatNumberChanging(global::System.Int32 value);
        partial void OnHeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HNS
        {
            get
            {
                return _HNS;
            }
            set
            {
                if (_HNS != value)
                {
                    OnHNSChanging(value);
                    ReportPropertyChanging("HNS");
                    _HNS = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HNS");
                    OnHNSChanged();
                }
            }
        }
        private global::System.Int32 _HNS;
        partial void OnHNSChanging(global::System.Int32 value);
        partial void OnHNSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitNumber
        {
            get
            {
                return _UnitNumber;
            }
            set
            {
                OnUnitNumberChanging(value);
                ReportPropertyChanging("UnitNumber");
                _UnitNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitNumber");
                OnUnitNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitNumber;
        partial void OnUnitNumberChanging(Nullable<global::System.Int32> value);
        partial void OnUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProgramNumber
        {
            get
            {
                return _ProgramNumber;
            }
            set
            {
                OnProgramNumberChanging(value);
                ReportPropertyChanging("ProgramNumber");
                _ProgramNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramNumber");
                OnProgramNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _ProgramNumber;
        partial void OnProgramNumberChanging(Nullable<global::System.Int32> value);
        partial void OnProgramNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LadleNumber
        {
            get
            {
                return _LadleNumber;
            }
            set
            {
                OnLadleNumberChanging(value);
                ReportPropertyChanging("LadleNumber");
                _LadleNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LadleNumber");
                OnLadleNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _LadleNumber;
        partial void OnLadleNumberChanging(Nullable<global::System.Int32> value);
        partial void OnLadleNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampStart
        {
            get
            {
                return _TimeStampStart;
            }
            set
            {
                OnTimeStampStartChanging(value);
                ReportPropertyChanging("TimeStampStart");
                _TimeStampStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampStart");
                OnTimeStampStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampStart;
        partial void OnTimeStampStartChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampEnd
        {
            get
            {
                return _TimeStampEnd;
            }
            set
            {
                OnTimeStampEndChanging(value);
                ReportPropertyChanging("TimeStampEnd");
                _TimeStampEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampEnd");
                OnTimeStampEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampEnd;
        partial void OnTimeStampEndChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampStartGMT
        {
            get
            {
                return _TimeStampStartGMT;
            }
            set
            {
                OnTimeStampStartGMTChanging(value);
                ReportPropertyChanging("TimeStampStartGMT");
                _TimeStampStartGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampStartGMT");
                OnTimeStampStartGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampStartGMT;
        partial void OnTimeStampStartGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampStartGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampEndGMT
        {
            get
            {
                return _TimeStampEndGMT;
            }
            set
            {
                OnTimeStampEndGMTChanging(value);
                ReportPropertyChanging("TimeStampEndGMT");
                _TimeStampEndGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampEndGMT");
                OnTimeStampEndGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampEndGMT;
        partial void OnTimeStampEndGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampEndGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> SpeedRatio
        {
            get
            {
                return _SpeedRatio;
            }
            set
            {
                OnSpeedRatioChanging(value);
                ReportPropertyChanging("SpeedRatio");
                _SpeedRatio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpeedRatio");
                OnSpeedRatioChanged();
            }
        }
        private Nullable<global::System.Single> _SpeedRatio;
        partial void OnSpeedRatioChanging(Nullable<global::System.Single> value);
        partial void OnSpeedRatioChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UnitSchema", Name="HMDesulph")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HMDesulph : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HMDesulph object.
        /// </summary>
        /// <param name="hMDesIndex">Initial value of the HMDesIndex property.</param>
        /// <param name="heatNumber">Initial value of the HeatNumber property.</param>
        /// <param name="hNS">Initial value of the HNS property.</param>
        public static HMDesulph CreateHMDesulph(global::System.Int32 hMDesIndex, global::System.Int32 heatNumber, global::System.Int32 hNS)
        {
            HMDesulph hMDesulph = new HMDesulph();
            hMDesulph.HMDesIndex = hMDesIndex;
            hMDesulph.HeatNumber = heatNumber;
            hMDesulph.HNS = hNS;
            return hMDesulph;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HMDesIndex
        {
            get
            {
                return _HMDesIndex;
            }
            set
            {
                if (_HMDesIndex != value)
                {
                    OnHMDesIndexChanging(value);
                    ReportPropertyChanging("HMDesIndex");
                    _HMDesIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HMDesIndex");
                    OnHMDesIndexChanged();
                }
            }
        }
        private global::System.Int32 _HMDesIndex;
        partial void OnHMDesIndexChanging(global::System.Int32 value);
        partial void OnHMDesIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                if (_HeatNumber != value)
                {
                    OnHeatNumberChanging(value);
                    ReportPropertyChanging("HeatNumber");
                    _HeatNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HeatNumber");
                    OnHeatNumberChanged();
                }
            }
        }
        private global::System.Int32 _HeatNumber;
        partial void OnHeatNumberChanging(global::System.Int32 value);
        partial void OnHeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HNS
        {
            get
            {
                return _HNS;
            }
            set
            {
                if (_HNS != value)
                {
                    OnHNSChanging(value);
                    ReportPropertyChanging("HNS");
                    _HNS = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HNS");
                    OnHNSChanged();
                }
            }
        }
        private global::System.Int32 _HNS;
        partial void OnHNSChanging(global::System.Int32 value);
        partial void OnHNSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitNumber
        {
            get
            {
                return _UnitNumber;
            }
            set
            {
                OnUnitNumberChanging(value);
                ReportPropertyChanging("UnitNumber");
                _UnitNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitNumber");
                OnUnitNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitNumber;
        partial void OnUnitNumberChanging(Nullable<global::System.Int32> value);
        partial void OnUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProgramNumber
        {
            get
            {
                return _ProgramNumber;
            }
            set
            {
                OnProgramNumberChanging(value);
                ReportPropertyChanging("ProgramNumber");
                _ProgramNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramNumber");
                OnProgramNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _ProgramNumber;
        partial void OnProgramNumberChanging(Nullable<global::System.Int32> value);
        partial void OnProgramNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampStart
        {
            get
            {
                return _TimeStampStart;
            }
            set
            {
                OnTimeStampStartChanging(value);
                ReportPropertyChanging("TimeStampStart");
                _TimeStampStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampStart");
                OnTimeStampStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampStart;
        partial void OnTimeStampStartChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampEnd
        {
            get
            {
                return _TimeStampEnd;
            }
            set
            {
                OnTimeStampEndChanging(value);
                ReportPropertyChanging("TimeStampEnd");
                _TimeStampEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampEnd");
                OnTimeStampEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampEnd;
        partial void OnTimeStampEndChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampStartGMT
        {
            get
            {
                return _TimeStampStartGMT;
            }
            set
            {
                OnTimeStampStartGMTChanging(value);
                ReportPropertyChanging("TimeStampStartGMT");
                _TimeStampStartGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampStartGMT");
                OnTimeStampStartGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampStartGMT;
        partial void OnTimeStampStartGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampStartGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampEndGMT
        {
            get
            {
                return _TimeStampEndGMT;
            }
            set
            {
                OnTimeStampEndGMTChanging(value);
                ReportPropertyChanging("TimeStampEndGMT");
                _TimeStampEndGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampEndGMT");
                OnTimeStampEndGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampEndGMT;
        partial void OnTimeStampEndGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampEndGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LadleNumber
        {
            get
            {
                return _LadleNumber;
            }
            set
            {
                OnLadleNumberChanging(value);
                ReportPropertyChanging("LadleNumber");
                _LadleNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LadleNumber");
                OnLadleNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _LadleNumber;
        partial void OnLadleNumberChanging(Nullable<global::System.Int32> value);
        partial void OnLadleNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> StartSulphur
        {
            get
            {
                return _StartSulphur;
            }
            set
            {
                OnStartSulphurChanging(value);
                ReportPropertyChanging("StartSulphur");
                _StartSulphur = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartSulphur");
                OnStartSulphurChanged();
            }
        }
        private Nullable<global::System.Single> _StartSulphur;
        partial void OnStartSulphurChanging(Nullable<global::System.Single> value);
        partial void OnStartSulphurChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> AimSulphur
        {
            get
            {
                return _AimSulphur;
            }
            set
            {
                OnAimSulphurChanging(value);
                ReportPropertyChanging("AimSulphur");
                _AimSulphur = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AimSulphur");
                OnAimSulphurChanged();
            }
        }
        private Nullable<global::System.Single> _AimSulphur;
        partial void OnAimSulphurChanging(Nullable<global::System.Single> value);
        partial void OnAimSulphurChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> TemperatureStart
        {
            get
            {
                return _TemperatureStart;
            }
            set
            {
                OnTemperatureStartChanging(value);
                ReportPropertyChanging("TemperatureStart");
                _TemperatureStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TemperatureStart");
                OnTemperatureStartChanged();
            }
        }
        private Nullable<global::System.Single> _TemperatureStart;
        partial void OnTemperatureStartChanging(Nullable<global::System.Single> value);
        partial void OnTemperatureStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> TemperatureEnd
        {
            get
            {
                return _TemperatureEnd;
            }
            set
            {
                OnTemperatureEndChanging(value);
                ReportPropertyChanging("TemperatureEnd");
                _TemperatureEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TemperatureEnd");
                OnTemperatureEndChanged();
            }
        }
        private Nullable<global::System.Single> _TemperatureEnd;
        partial void OnTemperatureEndChanging(Nullable<global::System.Single> value);
        partial void OnTemperatureEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeLastTemperature
        {
            get
            {
                return _TimeLastTemperature;
            }
            set
            {
                OnTimeLastTemperatureChanging(value);
                ReportPropertyChanging("TimeLastTemperature");
                _TimeLastTemperature = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeLastTemperature");
                OnTimeLastTemperatureChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeLastTemperature;
        partial void OnTimeLastTemperatureChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeLastTemperatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> HMWeight
        {
            get
            {
                return _HMWeight;
            }
            set
            {
                OnHMWeightChanging(value);
                ReportPropertyChanging("HMWeight");
                _HMWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HMWeight");
                OnHMWeightChanged();
            }
        }
        private Nullable<global::System.Single> _HMWeight;
        partial void OnHMWeightChanging(Nullable<global::System.Single> value);
        partial void OnHMWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> SkimLoss
        {
            get
            {
                return _SkimLoss;
            }
            set
            {
                OnSkimLossChanging(value);
                ReportPropertyChanging("SkimLoss");
                _SkimLoss = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SkimLoss");
                OnSkimLossChanged();
            }
        }
        private Nullable<global::System.Single> _SkimLoss;
        partial void OnSkimLossChanging(Nullable<global::System.Single> value);
        partial void OnSkimLossChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TreatmentCount
        {
            get
            {
                return _TreatmentCount;
            }
            set
            {
                OnTreatmentCountChanging(value);
                ReportPropertyChanging("TreatmentCount");
                _TreatmentCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TreatmentCount");
                OnTreatmentCountChanged();
            }
        }
        private Nullable<global::System.Int32> _TreatmentCount;
        partial void OnTreatmentCountChanging(Nullable<global::System.Int32> value);
        partial void OnTreatmentCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SkimCount
        {
            get
            {
                return _SkimCount;
            }
            set
            {
                OnSkimCountChanging(value);
                ReportPropertyChanging("SkimCount");
                _SkimCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SkimCount");
                OnSkimCountChanged();
            }
        }
        private Nullable<global::System.Int32> _SkimCount;
        partial void OnSkimCountChanging(Nullable<global::System.Int32> value);
        partial void OnSkimCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> LimeTotal
        {
            get
            {
                return _LimeTotal;
            }
            set
            {
                OnLimeTotalChanging(value);
                ReportPropertyChanging("LimeTotal");
                _LimeTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LimeTotal");
                OnLimeTotalChanged();
            }
        }
        private Nullable<global::System.Single> _LimeTotal;
        partial void OnLimeTotalChanging(Nullable<global::System.Single> value);
        partial void OnLimeTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> MgTotal
        {
            get
            {
                return _MgTotal;
            }
            set
            {
                OnMgTotalChanging(value);
                ReportPropertyChanging("MgTotal");
                _MgTotal = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MgTotal");
                OnMgTotalChanged();
            }
        }
        private Nullable<global::System.Single> _MgTotal;
        partial void OnMgTotalChanging(Nullable<global::System.Single> value);
        partial void OnMgTotalChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeCreated
        {
            get
            {
                return _TimeCreated;
            }
            set
            {
                OnTimeCreatedChanging(value);
                ReportPropertyChanging("TimeCreated");
                _TimeCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeCreated");
                OnTimeCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeCreated;
        partial void OnTimeCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeCreatedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UnitSchema", Name="HMDesulphReport")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HMDesulphReport : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HMDesulphReport object.
        /// </summary>
        /// <param name="hMDesReportIndex">Initial value of the HMDesReportIndex property.</param>
        /// <param name="heatNumber">Initial value of the HeatNumber property.</param>
        /// <param name="hNS">Initial value of the HNS property.</param>
        public static HMDesulphReport CreateHMDesulphReport(global::System.Int32 hMDesReportIndex, global::System.Int32 heatNumber, global::System.Int32 hNS)
        {
            HMDesulphReport hMDesulphReport = new HMDesulphReport();
            hMDesulphReport.HMDesReportIndex = hMDesReportIndex;
            hMDesulphReport.HeatNumber = heatNumber;
            hMDesulphReport.HNS = hNS;
            return hMDesulphReport;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HMDesReportIndex
        {
            get
            {
                return _HMDesReportIndex;
            }
            set
            {
                if (_HMDesReportIndex != value)
                {
                    OnHMDesReportIndexChanging(value);
                    ReportPropertyChanging("HMDesReportIndex");
                    _HMDesReportIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HMDesReportIndex");
                    OnHMDesReportIndexChanged();
                }
            }
        }
        private global::System.Int32 _HMDesReportIndex;
        partial void OnHMDesReportIndexChanging(global::System.Int32 value);
        partial void OnHMDesReportIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                if (_HeatNumber != value)
                {
                    OnHeatNumberChanging(value);
                    ReportPropertyChanging("HeatNumber");
                    _HeatNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HeatNumber");
                    OnHeatNumberChanged();
                }
            }
        }
        private global::System.Int32 _HeatNumber;
        partial void OnHeatNumberChanging(global::System.Int32 value);
        partial void OnHeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HNS
        {
            get
            {
                return _HNS;
            }
            set
            {
                if (_HNS != value)
                {
                    OnHNSChanging(value);
                    ReportPropertyChanging("HNS");
                    _HNS = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HNS");
                    OnHNSChanged();
                }
            }
        }
        private global::System.Int32 _HNS;
        partial void OnHNSChanging(global::System.Int32 value);
        partial void OnHNSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitNumber
        {
            get
            {
                return _UnitNumber;
            }
            set
            {
                OnUnitNumberChanging(value);
                ReportPropertyChanging("UnitNumber");
                _UnitNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitNumber");
                OnUnitNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitNumber;
        partial void OnUnitNumberChanging(Nullable<global::System.Int32> value);
        partial void OnUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStamp
        {
            get
            {
                return _TimeStamp;
            }
            set
            {
                OnTimeStampChanging(value);
                ReportPropertyChanging("TimeStamp");
                _TimeStamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStamp");
                OnTimeStampChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStamp;
        partial void OnTimeStampChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampGMT
        {
            get
            {
                return _TimeStampGMT;
            }
            set
            {
                OnTimeStampGMTChanging(value);
                ReportPropertyChanging("TimeStampGMT");
                _TimeStampGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampGMT");
                OnTimeStampGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampGMT;
        partial void OnTimeStampGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> StartSulphur
        {
            get
            {
                return _StartSulphur;
            }
            set
            {
                OnStartSulphurChanging(value);
                ReportPropertyChanging("StartSulphur");
                _StartSulphur = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartSulphur");
                OnStartSulphurChanged();
            }
        }
        private Nullable<global::System.Single> _StartSulphur;
        partial void OnStartSulphurChanging(Nullable<global::System.Single> value);
        partial void OnStartSulphurChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> AimSulphur
        {
            get
            {
                return _AimSulphur;
            }
            set
            {
                OnAimSulphurChanging(value);
                ReportPropertyChanging("AimSulphur");
                _AimSulphur = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AimSulphur");
                OnAimSulphurChanged();
            }
        }
        private Nullable<global::System.Single> _AimSulphur;
        partial void OnAimSulphurChanging(Nullable<global::System.Single> value);
        partial void OnAimSulphurChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> LimeDemand
        {
            get
            {
                return _LimeDemand;
            }
            set
            {
                OnLimeDemandChanging(value);
                ReportPropertyChanging("LimeDemand");
                _LimeDemand = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LimeDemand");
                OnLimeDemandChanged();
            }
        }
        private Nullable<global::System.Single> _LimeDemand;
        partial void OnLimeDemandChanging(Nullable<global::System.Single> value);
        partial void OnLimeDemandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> LimeActual
        {
            get
            {
                return _LimeActual;
            }
            set
            {
                OnLimeActualChanging(value);
                ReportPropertyChanging("LimeActual");
                _LimeActual = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LimeActual");
                OnLimeActualChanged();
            }
        }
        private Nullable<global::System.Single> _LimeActual;
        partial void OnLimeActualChanging(Nullable<global::System.Single> value);
        partial void OnLimeActualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> MgDemand
        {
            get
            {
                return _MgDemand;
            }
            set
            {
                OnMgDemandChanging(value);
                ReportPropertyChanging("MgDemand");
                _MgDemand = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MgDemand");
                OnMgDemandChanged();
            }
        }
        private Nullable<global::System.Single> _MgDemand;
        partial void OnMgDemandChanging(Nullable<global::System.Single> value);
        partial void OnMgDemandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> MgActual
        {
            get
            {
                return _MgActual;
            }
            set
            {
                OnMgActualChanging(value);
                ReportPropertyChanging("MgActual");
                _MgActual = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MgActual");
                OnMgActualChanged();
            }
        }
        private Nullable<global::System.Single> _MgActual;
        partial void OnMgActualChanging(Nullable<global::System.Single> value);
        partial void OnMgActualChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeCreated
        {
            get
            {
                return _TimeCreated;
            }
            set
            {
                OnTimeCreatedChanging(value);
                ReportPropertyChanging("TimeCreated");
                _TimeCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeCreated");
                OnTimeCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeCreated;
        partial void OnTimeCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeCreatedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UnitSchema", Name="HMPour")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HMPour : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HMPour object.
        /// </summary>
        /// <param name="hMPourIndex">Initial value of the HMPourIndex property.</param>
        /// <param name="heatNumber">Initial value of the HeatNumber property.</param>
        /// <param name="hNS">Initial value of the HNS property.</param>
        public static HMPour CreateHMPour(global::System.Int32 hMPourIndex, global::System.Int32 heatNumber, global::System.Int32 hNS)
        {
            HMPour hMPour = new HMPour();
            hMPour.HMPourIndex = hMPourIndex;
            hMPour.HeatNumber = heatNumber;
            hMPour.HNS = hNS;
            return hMPour;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HMPourIndex
        {
            get
            {
                return _HMPourIndex;
            }
            set
            {
                if (_HMPourIndex != value)
                {
                    OnHMPourIndexChanging(value);
                    ReportPropertyChanging("HMPourIndex");
                    _HMPourIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HMPourIndex");
                    OnHMPourIndexChanged();
                }
            }
        }
        private global::System.Int32 _HMPourIndex;
        partial void OnHMPourIndexChanging(global::System.Int32 value);
        partial void OnHMPourIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                if (_HeatNumber != value)
                {
                    OnHeatNumberChanging(value);
                    ReportPropertyChanging("HeatNumber");
                    _HeatNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HeatNumber");
                    OnHeatNumberChanged();
                }
            }
        }
        private global::System.Int32 _HeatNumber;
        partial void OnHeatNumberChanging(global::System.Int32 value);
        partial void OnHeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HNS
        {
            get
            {
                return _HNS;
            }
            set
            {
                if (_HNS != value)
                {
                    OnHNSChanging(value);
                    ReportPropertyChanging("HNS");
                    _HNS = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HNS");
                    OnHNSChanged();
                }
            }
        }
        private global::System.Int32 _HNS;
        partial void OnHNSChanging(global::System.Int32 value);
        partial void OnHNSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitNumber
        {
            get
            {
                return _UnitNumber;
            }
            set
            {
                OnUnitNumberChanging(value);
                ReportPropertyChanging("UnitNumber");
                _UnitNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitNumber");
                OnUnitNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitNumber;
        partial void OnUnitNumberChanging(Nullable<global::System.Int32> value);
        partial void OnUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProgramNumber
        {
            get
            {
                return _ProgramNumber;
            }
            set
            {
                OnProgramNumberChanging(value);
                ReportPropertyChanging("ProgramNumber");
                _ProgramNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramNumber");
                OnProgramNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _ProgramNumber;
        partial void OnProgramNumberChanging(Nullable<global::System.Int32> value);
        partial void OnProgramNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampStart
        {
            get
            {
                return _TimeStampStart;
            }
            set
            {
                OnTimeStampStartChanging(value);
                ReportPropertyChanging("TimeStampStart");
                _TimeStampStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampStart");
                OnTimeStampStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampStart;
        partial void OnTimeStampStartChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampEnd
        {
            get
            {
                return _TimeStampEnd;
            }
            set
            {
                OnTimeStampEndChanging(value);
                ReportPropertyChanging("TimeStampEnd");
                _TimeStampEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampEnd");
                OnTimeStampEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampEnd;
        partial void OnTimeStampEndChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampStartGMT
        {
            get
            {
                return _TimeStampStartGMT;
            }
            set
            {
                OnTimeStampStartGMTChanging(value);
                ReportPropertyChanging("TimeStampStartGMT");
                _TimeStampStartGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampStartGMT");
                OnTimeStampStartGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampStartGMT;
        partial void OnTimeStampStartGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampStartGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampEndGMT
        {
            get
            {
                return _TimeStampEndGMT;
            }
            set
            {
                OnTimeStampEndGMTChanging(value);
                ReportPropertyChanging("TimeStampEndGMT");
                _TimeStampEndGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampEndGMT");
                OnTimeStampEndGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampEndGMT;
        partial void OnTimeStampEndGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampEndGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LadleNumber
        {
            get
            {
                return _LadleNumber;
            }
            set
            {
                OnLadleNumberChanging(value);
                ReportPropertyChanging("LadleNumber");
                _LadleNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LadleNumber");
                OnLadleNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _LadleNumber;
        partial void OnLadleNumberChanging(Nullable<global::System.Int32> value);
        partial void OnLadleNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HMLadleLife
        {
            get
            {
                return _HMLadleLife;
            }
            set
            {
                OnHMLadleLifeChanging(value);
                ReportPropertyChanging("HMLadleLife");
                _HMLadleLife = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HMLadleLife");
                OnHMLadleLifeChanged();
            }
        }
        private Nullable<global::System.Int32> _HMLadleLife;
        partial void OnHMLadleLifeChanging(Nullable<global::System.Int32> value);
        partial void OnHMLadleLifeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> HMWeight
        {
            get
            {
                return _HMWeight;
            }
            set
            {
                OnHMWeightChanging(value);
                ReportPropertyChanging("HMWeight");
                _HMWeight = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HMWeight");
                OnHMWeightChanged();
            }
        }
        private Nullable<global::System.Single> _HMWeight;
        partial void OnHMWeightChanging(Nullable<global::System.Single> value);
        partial void OnHMWeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> HMLastTemperature
        {
            get
            {
                return _HMLastTemperature;
            }
            set
            {
                OnHMLastTemperatureChanging(value);
                ReportPropertyChanging("HMLastTemperature");
                _HMLastTemperature = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HMLastTemperature");
                OnHMLastTemperatureChanged();
            }
        }
        private Nullable<global::System.Single> _HMLastTemperature;
        partial void OnHMLastTemperatureChanging(Nullable<global::System.Single> value);
        partial void OnHMLastTemperatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeLastTemperature
        {
            get
            {
                return _TimeLastTemperature;
            }
            set
            {
                OnTimeLastTemperatureChanging(value);
                ReportPropertyChanging("TimeLastTemperature");
                _TimeLastTemperature = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeLastTemperature");
                OnTimeLastTemperatureChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeLastTemperature;
        partial void OnTimeLastTemperatureChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeLastTemperatureChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeCreated
        {
            get
            {
                return _TimeCreated;
            }
            set
            {
                OnTimeCreatedChanging(value);
                ReportPropertyChanging("TimeCreated");
                _TimeCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeCreated");
                OnTimeCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeCreated;
        partial void OnTimeCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeCreatedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UnitSchema", Name="SecSteel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SecSteel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SecSteel object.
        /// </summary>
        /// <param name="secSteelIndex">Initial value of the SecSteelIndex property.</param>
        /// <param name="heatNumber">Initial value of the HeatNumber property.</param>
        /// <param name="hNS">Initial value of the HNS property.</param>
        public static SecSteel CreateSecSteel(global::System.Int32 secSteelIndex, global::System.Int32 heatNumber, global::System.Int32 hNS)
        {
            SecSteel secSteel = new SecSteel();
            secSteel.SecSteelIndex = secSteelIndex;
            secSteel.HeatNumber = heatNumber;
            secSteel.HNS = hNS;
            return secSteel;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SecSteelIndex
        {
            get
            {
                return _SecSteelIndex;
            }
            set
            {
                if (_SecSteelIndex != value)
                {
                    OnSecSteelIndexChanging(value);
                    ReportPropertyChanging("SecSteelIndex");
                    _SecSteelIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SecSteelIndex");
                    OnSecSteelIndexChanged();
                }
            }
        }
        private global::System.Int32 _SecSteelIndex;
        partial void OnSecSteelIndexChanging(global::System.Int32 value);
        partial void OnSecSteelIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                if (_HeatNumber != value)
                {
                    OnHeatNumberChanging(value);
                    ReportPropertyChanging("HeatNumber");
                    _HeatNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HeatNumber");
                    OnHeatNumberChanged();
                }
            }
        }
        private global::System.Int32 _HeatNumber;
        partial void OnHeatNumberChanging(global::System.Int32 value);
        partial void OnHeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HNS
        {
            get
            {
                return _HNS;
            }
            set
            {
                if (_HNS != value)
                {
                    OnHNSChanging(value);
                    ReportPropertyChanging("HNS");
                    _HNS = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HNS");
                    OnHNSChanged();
                }
            }
        }
        private global::System.Int32 _HNS;
        partial void OnHNSChanging(global::System.Int32 value);
        partial void OnHNSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitNumber
        {
            get
            {
                return _UnitNumber;
            }
            set
            {
                OnUnitNumberChanging(value);
                ReportPropertyChanging("UnitNumber");
                _UnitNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitNumber");
                OnUnitNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitNumber;
        partial void OnUnitNumberChanging(Nullable<global::System.Int32> value);
        partial void OnUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProgramNumber
        {
            get
            {
                return _ProgramNumber;
            }
            set
            {
                OnProgramNumberChanging(value);
                ReportPropertyChanging("ProgramNumber");
                _ProgramNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramNumber");
                OnProgramNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _ProgramNumber;
        partial void OnProgramNumberChanging(Nullable<global::System.Int32> value);
        partial void OnProgramNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TImeStampStart
        {
            get
            {
                return _TImeStampStart;
            }
            set
            {
                OnTImeStampStartChanging(value);
                ReportPropertyChanging("TImeStampStart");
                _TImeStampStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TImeStampStart");
                OnTImeStampStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _TImeStampStart;
        partial void OnTImeStampStartChanging(Nullable<global::System.DateTime> value);
        partial void OnTImeStampStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampEnd
        {
            get
            {
                return _TimeStampEnd;
            }
            set
            {
                OnTimeStampEndChanging(value);
                ReportPropertyChanging("TimeStampEnd");
                _TimeStampEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampEnd");
                OnTimeStampEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampEnd;
        partial void OnTimeStampEndChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampStartGMT
        {
            get
            {
                return _TimeStampStartGMT;
            }
            set
            {
                OnTimeStampStartGMTChanging(value);
                ReportPropertyChanging("TimeStampStartGMT");
                _TimeStampStartGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampStartGMT");
                OnTimeStampStartGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampStartGMT;
        partial void OnTimeStampStartGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampStartGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampEndGMT
        {
            get
            {
                return _TimeStampEndGMT;
            }
            set
            {
                OnTimeStampEndGMTChanging(value);
                ReportPropertyChanging("TimeStampEndGMT");
                _TimeStampEndGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampEndGMT");
                OnTimeStampEndGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampEndGMT;
        partial void OnTimeStampEndGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampEndGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeCreated
        {
            get
            {
                return _TimeCreated;
            }
            set
            {
                OnTimeCreatedChanging(value);
                ReportPropertyChanging("TimeCreated");
                _TimeCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeCreated");
                OnTimeCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeCreated;
        partial void OnTimeCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> SlagDepth
        {
            get
            {
                return _SlagDepth;
            }
            set
            {
                OnSlagDepthChanging(value);
                ReportPropertyChanging("SlagDepth");
                _SlagDepth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlagDepth");
                OnSlagDepthChanged();
            }
        }
        private Nullable<global::System.Int16> _SlagDepth;
        partial void OnSlagDepthChanging(Nullable<global::System.Int16> value);
        partial void OnSlagDepthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Freeboard
        {
            get
            {
                return _Freeboard;
            }
            set
            {
                OnFreeboardChanging(value);
                ReportPropertyChanging("Freeboard");
                _Freeboard = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Freeboard");
                OnFreeboardChanged();
            }
        }
        private Nullable<global::System.Int16> _Freeboard;
        partial void OnFreeboardChanging(Nullable<global::System.Int16> value);
        partial void OnFreeboardChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="UnitSchema", Name="Vessel")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Vessel : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Vessel object.
        /// </summary>
        /// <param name="vesselIndex">Initial value of the VesselIndex property.</param>
        /// <param name="heatNumber">Initial value of the HeatNumber property.</param>
        /// <param name="hNS">Initial value of the HNS property.</param>
        public static Vessel CreateVessel(global::System.Int32 vesselIndex, global::System.Int32 heatNumber, global::System.Int32 hNS)
        {
            Vessel vessel = new Vessel();
            vessel.VesselIndex = vesselIndex;
            vessel.HeatNumber = heatNumber;
            vessel.HNS = hNS;
            return vessel;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VesselIndex
        {
            get
            {
                return _VesselIndex;
            }
            set
            {
                if (_VesselIndex != value)
                {
                    OnVesselIndexChanging(value);
                    ReportPropertyChanging("VesselIndex");
                    _VesselIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("VesselIndex");
                    OnVesselIndexChanged();
                }
            }
        }
        private global::System.Int32 _VesselIndex;
        partial void OnVesselIndexChanging(global::System.Int32 value);
        partial void OnVesselIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                if (_HeatNumber != value)
                {
                    OnHeatNumberChanging(value);
                    ReportPropertyChanging("HeatNumber");
                    _HeatNumber = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HeatNumber");
                    OnHeatNumberChanged();
                }
            }
        }
        private global::System.Int32 _HeatNumber;
        partial void OnHeatNumberChanging(global::System.Int32 value);
        partial void OnHeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HNS
        {
            get
            {
                return _HNS;
            }
            set
            {
                if (_HNS != value)
                {
                    OnHNSChanging(value);
                    ReportPropertyChanging("HNS");
                    _HNS = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HNS");
                    OnHNSChanged();
                }
            }
        }
        private global::System.Int32 _HNS;
        partial void OnHNSChanging(global::System.Int32 value);
        partial void OnHNSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitNumber
        {
            get
            {
                return _UnitNumber;
            }
            set
            {
                OnUnitNumberChanging(value);
                ReportPropertyChanging("UnitNumber");
                _UnitNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitNumber");
                OnUnitNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitNumber;
        partial void OnUnitNumberChanging(Nullable<global::System.Int32> value);
        partial void OnUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProgramNumber
        {
            get
            {
                return _ProgramNumber;
            }
            set
            {
                OnProgramNumberChanging(value);
                ReportPropertyChanging("ProgramNumber");
                _ProgramNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramNumber");
                OnProgramNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _ProgramNumber;
        partial void OnProgramNumberChanging(Nullable<global::System.Int32> value);
        partial void OnProgramNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BlowCount
        {
            get
            {
                return _BlowCount;
            }
            set
            {
                OnBlowCountChanging(value);
                ReportPropertyChanging("BlowCount");
                _BlowCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BlowCount");
                OnBlowCountChanged();
            }
        }
        private Nullable<global::System.Int32> _BlowCount;
        partial void OnBlowCountChanging(Nullable<global::System.Int32> value);
        partial void OnBlowCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TapCount
        {
            get
            {
                return _TapCount;
            }
            set
            {
                OnTapCountChanging(value);
                ReportPropertyChanging("TapCount");
                _TapCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TapCount");
                OnTapCountChanged();
            }
        }
        private Nullable<global::System.Int32> _TapCount;
        partial void OnTapCountChanging(Nullable<global::System.Int32> value);
        partial void OnTapCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TImeStampStart
        {
            get
            {
                return _TImeStampStart;
            }
            set
            {
                OnTImeStampStartChanging(value);
                ReportPropertyChanging("TImeStampStart");
                _TImeStampStart = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TImeStampStart");
                OnTImeStampStartChanged();
            }
        }
        private Nullable<global::System.DateTime> _TImeStampStart;
        partial void OnTImeStampStartChanging(Nullable<global::System.DateTime> value);
        partial void OnTImeStampStartChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampEnd
        {
            get
            {
                return _TimeStampEnd;
            }
            set
            {
                OnTimeStampEndChanging(value);
                ReportPropertyChanging("TimeStampEnd");
                _TimeStampEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampEnd");
                OnTimeStampEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampEnd;
        partial void OnTimeStampEndChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampEndChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampStartGMT
        {
            get
            {
                return _TimeStampStartGMT;
            }
            set
            {
                OnTimeStampStartGMTChanging(value);
                ReportPropertyChanging("TimeStampStartGMT");
                _TimeStampStartGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampStartGMT");
                OnTimeStampStartGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampStartGMT;
        partial void OnTimeStampStartGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampStartGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeStampEndGMT
        {
            get
            {
                return _TimeStampEndGMT;
            }
            set
            {
                OnTimeStampEndGMTChanging(value);
                ReportPropertyChanging("TimeStampEndGMT");
                _TimeStampEndGMT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeStampEndGMT");
                OnTimeStampEndGMTChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeStampEndGMT;
        partial void OnTimeStampEndGMTChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeStampEndGMTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> TimeCreated
        {
            get
            {
                return _TimeCreated;
            }
            set
            {
                OnTimeCreatedChanging(value);
                ReportPropertyChanging("TimeCreated");
                _TimeCreated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimeCreated");
                OnTimeCreatedChanged();
            }
        }
        private Nullable<global::System.DateTime> _TimeCreated;
        partial void OnTimeCreatedChanging(Nullable<global::System.DateTime> value);
        partial void OnTimeCreatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartChargeTime
        {
            get
            {
                return _StartChargeTime;
            }
            set
            {
                OnStartChargeTimeChanging(value);
                ReportPropertyChanging("StartChargeTime");
                _StartChargeTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartChargeTime");
                OnStartChargeTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartChargeTime;
        partial void OnStartChargeTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartChargeTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartBlowTime
        {
            get
            {
                return _StartBlowTime;
            }
            set
            {
                OnStartBlowTimeChanging(value);
                ReportPropertyChanging("StartBlowTime");
                _StartBlowTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartBlowTime");
                OnStartBlowTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartBlowTime;
        partial void OnStartBlowTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartBlowTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndBlowTime
        {
            get
            {
                return _EndBlowTime;
            }
            set
            {
                OnEndBlowTimeChanging(value);
                ReportPropertyChanging("EndBlowTime");
                _EndBlowTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndBlowTime");
                OnEndBlowTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndBlowTime;
        partial void OnEndBlowTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndBlowTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartTapTime
        {
            get
            {
                return _StartTapTime;
            }
            set
            {
                OnStartTapTimeChanging(value);
                ReportPropertyChanging("StartTapTime");
                _StartTapTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartTapTime");
                OnStartTapTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartTapTime;
        partial void OnStartTapTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnStartTapTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> EndTapTime
        {
            get
            {
                return _EndTapTime;
            }
            set
            {
                OnEndTapTimeChanging(value);
                ReportPropertyChanging("EndTapTime");
                _EndTapTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EndTapTime");
                OnEndTapTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _EndTapTime;
        partial void OnEndTapTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnEndTapTimeChanged();

        #endregion

    
    }

    #endregion

    
}
