//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ElvisDataModel.EDMX
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ElvisDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ElvisDBEntities object using the connection string found in the 'ElvisDBEntities' section of the application configuration file.
        /// </summary>
        public ElvisDBEntities() : base("name=ElvisDBEntities", "ElvisDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ElvisDBEntities object.
        /// </summary>
        public ElvisDBEntities(string connectionString) : base(connectionString, "ElvisDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ElvisDBEntities object.
        /// </summary>
        public ElvisDBEntities(EntityConnection connection) : base(connection, "ElvisDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="scheduleDate">No Metadata Documentation available.</param>
        public ObjectResult<CastersProductionItem> GetDailyActualCasterHeats(Nullable<global::System.DateTime> scheduleDate)
        {
            ObjectParameter scheduleDateParameter;
            if (scheduleDate.HasValue)
            {
                scheduleDateParameter = new ObjectParameter("scheduleDate", scheduleDate);
            }
            else
            {
                scheduleDateParameter = new ObjectParameter("scheduleDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<CastersProductionItem>("GetDailyActualCasterHeats", scheduleDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="scheduleDate">No Metadata Documentation available.</param>
        /// <param name="startHour">No Metadata Documentation available.</param>
        /// <param name="planHour">No Metadata Documentation available.</param>
        public ObjectResult<CastersScheduleItem> GetDailyPlannedCasterHeats(Nullable<global::System.DateTime> scheduleDate, Nullable<global::System.Int32> startHour, Nullable<global::System.Int32> planHour)
        {
            ObjectParameter scheduleDateParameter;
            if (scheduleDate.HasValue)
            {
                scheduleDateParameter = new ObjectParameter("scheduleDate", scheduleDate);
            }
            else
            {
                scheduleDateParameter = new ObjectParameter("scheduleDate", typeof(global::System.DateTime));
            }
    
            ObjectParameter startHourParameter;
            if (startHour.HasValue)
            {
                startHourParameter = new ObjectParameter("startHour", startHour);
            }
            else
            {
                startHourParameter = new ObjectParameter("startHour", typeof(global::System.Int32));
            }
    
            ObjectParameter planHourParameter;
            if (planHour.HasValue)
            {
                planHourParameter = new ObjectParameter("planHour", planHour);
            }
            else
            {
                planHourParameter = new ObjectParameter("planHour", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<CastersScheduleItem>("GetDailyPlannedCasterHeats", scheduleDateParameter, startHourParameter, planHourParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="shiftStartDate">No Metadata Documentation available.</param>
        public ObjectResult<CasterTotalsByShiftForDay> GetCasterTotalsByShiftForDay(Nullable<global::System.DateTime> shiftStartDate)
        {
            ObjectParameter shiftStartDateParameter;
            if (shiftStartDate.HasValue)
            {
                shiftStartDateParameter = new ObjectParameter("shiftStartDate", shiftStartDate);
            }
            else
            {
                shiftStartDateParameter = new ObjectParameter("shiftStartDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<CasterTotalsByShiftForDay>("GetCasterTotalsByShiftForDay", shiftStartDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="productionDate">No Metadata Documentation available.</param>
        public ObjectResult<CasterTotalsByShiftForWeek> GetCasterTotalsByShiftForWeek(Nullable<global::System.DateTime> productionDate)
        {
            ObjectParameter productionDateParameter;
            if (productionDate.HasValue)
            {
                productionDateParameter = new ObjectParameter("productionDate", productionDate);
            }
            else
            {
                productionDateParameter = new ObjectParameter("productionDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<CasterTotalsByShiftForWeek>("GetCasterTotalsByShiftForWeek", productionDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="productionDate">No Metadata Documentation available.</param>
        public ObjectResult<CasterTotalsByShiftForDay> GetDayShiftPlanByCaster(Nullable<global::System.DateTime> productionDate)
        {
            ObjectParameter productionDateParameter;
            if (productionDate.HasValue)
            {
                productionDateParameter = new ObjectParameter("productionDate", productionDate);
            }
            else
            {
                productionDateParameter = new ObjectParameter("productionDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<CasterTotalsByShiftForDay>("GetDayShiftPlanByCaster", productionDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="productionDate">No Metadata Documentation available.</param>
        public ObjectResult<CasterTotalsByShiftForDay> GetNightShiftPlanByCaster(Nullable<global::System.DateTime> productionDate)
        {
            ObjectParameter productionDateParameter;
            if (productionDate.HasValue)
            {
                productionDateParameter = new ObjectParameter("productionDate", productionDate);
            }
            else
            {
                productionDateParameter = new ObjectParameter("productionDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<CasterTotalsByShiftForDay>("GetNightShiftPlanByCaster", productionDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="productionDate">No Metadata Documentation available.</param>
        public ObjectResult<ShiftStartHeatPlanItem> GetDayShiftPlan(Nullable<global::System.DateTime> productionDate)
        {
            ObjectParameter productionDateParameter;
            if (productionDate.HasValue)
            {
                productionDateParameter = new ObjectParameter("productionDate", productionDate);
            }
            else
            {
                productionDateParameter = new ObjectParameter("productionDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<ShiftStartHeatPlanItem>("GetDayShiftPlan", productionDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="productionDate">No Metadata Documentation available.</param>
        public ObjectResult<ShiftStartHeatPlanItem> GetNightShiftPlan(Nullable<global::System.DateTime> productionDate)
        {
            ObjectParameter productionDateParameter;
            if (productionDate.HasValue)
            {
                productionDateParameter = new ObjectParameter("productionDate", productionDate);
            }
            else
            {
                productionDateParameter = new ObjectParameter("productionDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<ShiftStartHeatPlanItem>("GetNightShiftPlan", productionDateParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<TodayDate> GetTodayDate()
        {
            return base.ExecuteFunction<TodayDate>("GetTodayDate");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="i">No Metadata Documentation available.</param>
        public ObjectResult<global::System.String> GetParameter(Nullable<global::System.Int32> i)
        {
            ObjectParameter iParameter;
            if (i.HasValue)
            {
                iParameter = new ObjectParameter("i", i);
            }
            else
            {
                iParameter = new ObjectParameter("i", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<global::System.String>("GetParameter", iParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="i">No Metadata Documentation available.</param>
        /// <param name="v">No Metadata Documentation available.</param>
        public int SetParameter(Nullable<global::System.Int32> i, global::System.String v)
        {
            ObjectParameter iParameter;
            if (i.HasValue)
            {
                iParameter = new ObjectParameter("i", i);
            }
            else
            {
                iParameter = new ObjectParameter("i", typeof(global::System.Int32));
            }
    
            ObjectParameter vParameter;
            if (v != null)
            {
                vParameter = new ObjectParameter("v", v);
            }
            else
            {
                vParameter = new ObjectParameter("v", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("SetParameter", iParameter, vParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="scheduleDate">No Metadata Documentation available.</param>
        public ObjectResult<CastersProductionItem> GetDailyActualCasterHeats7AM(Nullable<global::System.DateTime> scheduleDate)
        {
            ObjectParameter scheduleDateParameter;
            if (scheduleDate.HasValue)
            {
                scheduleDateParameter = new ObjectParameter("scheduleDate", scheduleDate);
            }
            else
            {
                scheduleDateParameter = new ObjectParameter("scheduleDate", typeof(global::System.DateTime));
            }
    
            return base.ExecuteFunction<CastersProductionItem>("GetDailyActualCasterHeats7AM", scheduleDateParameter);
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ElvisDBModel", Name="CastersProductionItem")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class CastersProductionItem : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CastersProductionItem object.
        /// </summary>
        /// <param name="heatNumber">Initial value of the HeatNumber property.</param>
        /// <param name="unitNumber">Initial value of the UnitNumber property.</param>
        /// <param name="actualStartDate">Initial value of the ActualStartDate property.</param>
        /// <param name="hNS">Initial value of the HNS property.</param>
        public static CastersProductionItem CreateCastersProductionItem(global::System.Int32 heatNumber, global::System.Int32 unitNumber, global::System.DateTime actualStartDate, global::System.Int32 hNS)
        {
            CastersProductionItem castersProductionItem = new CastersProductionItem();
            castersProductionItem.HeatNumber = heatNumber;
            castersProductionItem.UnitNumber = unitNumber;
            castersProductionItem.ActualStartDate = actualStartDate;
            castersProductionItem.HNS = hNS;
            return castersProductionItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                OnHeatNumberChanging(value);
                ReportPropertyChanging("HeatNumber");
                _HeatNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeatNumber");
                OnHeatNumberChanged();
            }
        }
        private global::System.Int32 _HeatNumber;
        partial void OnHeatNumberChanging(global::System.Int32 value);
        partial void OnHeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProgramNumber
        {
            get
            {
                return _ProgramNumber;
            }
            set
            {
                OnProgramNumberChanging(value);
                ReportPropertyChanging("ProgramNumber");
                _ProgramNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramNumber");
                OnProgramNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _ProgramNumber;
        partial void OnProgramNumberChanging(Nullable<global::System.Int32> value);
        partial void OnProgramNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Grade1
        {
            get
            {
                return _Grade1;
            }
            set
            {
                OnGrade1Changing(value);
                ReportPropertyChanging("Grade1");
                _Grade1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Grade1");
                OnGrade1Changed();
            }
        }
        private Nullable<global::System.Int32> _Grade1;
        partial void OnGrade1Changing(Nullable<global::System.Int32> value);
        partial void OnGrade1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ActualCaster
        {
            get
            {
                return _ActualCaster;
            }
            set
            {
                OnActualCasterChanging(value);
                ReportPropertyChanging("ActualCaster");
                _ActualCaster = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ActualCaster");
                OnActualCasterChanged();
            }
        }
        private global::System.String _ActualCaster;
        partial void OnActualCasterChanging(global::System.String value);
        partial void OnActualCasterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CasterNumber
        {
            get
            {
                return _CasterNumber;
            }
            set
            {
                OnCasterNumberChanging(value);
                ReportPropertyChanging("CasterNumber");
                _CasterNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CasterNumber");
                OnCasterNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _CasterNumber;
        partial void OnCasterNumberChanging(Nullable<global::System.Int32> value);
        partial void OnCasterNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UnitNumber
        {
            get
            {
                return _UnitNumber;
            }
            set
            {
                OnUnitNumberChanging(value);
                ReportPropertyChanging("UnitNumber");
                _UnitNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitNumber");
                OnUnitNumberChanged();
            }
        }
        private global::System.Int32 _UnitNumber;
        partial void OnUnitNumberChanging(global::System.Int32 value);
        partial void OnUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ActualStartDate
        {
            get
            {
                return _ActualStartDate;
            }
            set
            {
                OnActualStartDateChanging(value);
                ReportPropertyChanging("ActualStartDate");
                _ActualStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActualStartDate");
                OnActualStartDateChanged();
            }
        }
        private global::System.DateTime _ActualStartDate;
        partial void OnActualStartDateChanging(global::System.DateTime value);
        partial void OnActualStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ActualEndDate
        {
            get
            {
                return _ActualEndDate;
            }
            set
            {
                OnActualEndDateChanging(value);
                ReportPropertyChanging("ActualEndDate");
                _ActualEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ActualEndDate");
                OnActualEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ActualEndDate;
        partial void OnActualEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnActualEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HNS
        {
            get
            {
                return _HNS;
            }
            set
            {
                OnHNSChanging(value);
                ReportPropertyChanging("HNS");
                _HNS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HNS");
                OnHNSChanged();
            }
        }
        private global::System.Int32 _HNS;
        partial void OnHNSChanging(global::System.Int32 value);
        partial void OnHNSChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ElvisDBModel", Name="CastersScheduleItem")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class CastersScheduleItem : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CastersScheduleItem object.
        /// </summary>
        /// <param name="heatNumber">Initial value of the HeatNumber property.</param>
        /// <param name="hNS">Initial value of the HNS property.</param>
        public static CastersScheduleItem CreateCastersScheduleItem(global::System.Int32 heatNumber, global::System.Int32 hNS)
        {
            CastersScheduleItem castersScheduleItem = new CastersScheduleItem();
            castersScheduleItem.HeatNumber = heatNumber;
            castersScheduleItem.HNS = hNS;
            return castersScheduleItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                OnHeatNumberChanging(value);
                ReportPropertyChanging("HeatNumber");
                _HeatNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeatNumber");
                OnHeatNumberChanged();
            }
        }
        private global::System.Int32 _HeatNumber;
        partial void OnHeatNumberChanging(global::System.Int32 value);
        partial void OnHeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ProgramNumber
        {
            get
            {
                return _ProgramNumber;
            }
            set
            {
                OnProgramNumberChanging(value);
                ReportPropertyChanging("ProgramNumber");
                _ProgramNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramNumber");
                OnProgramNumberChanged();
            }
        }
        private Nullable<global::System.Int16> _ProgramNumber;
        partial void OnProgramNumberChanging(Nullable<global::System.Int16> value);
        partial void OnProgramNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Grade1
        {
            get
            {
                return _Grade1;
            }
            set
            {
                OnGrade1Changing(value);
                ReportPropertyChanging("Grade1");
                _Grade1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Grade1");
                OnGrade1Changed();
            }
        }
        private Nullable<global::System.Int16> _Grade1;
        partial void OnGrade1Changing(Nullable<global::System.Int16> value);
        partial void OnGrade1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PlannedCaster
        {
            get
            {
                return _PlannedCaster;
            }
            set
            {
                OnPlannedCasterChanging(value);
                ReportPropertyChanging("PlannedCaster");
                _PlannedCaster = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PlannedCaster");
                OnPlannedCasterChanged();
            }
        }
        private global::System.String _PlannedCaster;
        partial void OnPlannedCasterChanging(global::System.String value);
        partial void OnPlannedCasterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> CasterNumber
        {
            get
            {
                return _CasterNumber;
            }
            set
            {
                OnCasterNumberChanging(value);
                ReportPropertyChanging("CasterNumber");
                _CasterNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CasterNumber");
                OnCasterNumberChanged();
            }
        }
        private Nullable<global::System.Int16> _CasterNumber;
        partial void OnCasterNumberChanging(Nullable<global::System.Int16> value);
        partial void OnCasterNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> UnitNumber
        {
            get
            {
                return _UnitNumber;
            }
            set
            {
                OnUnitNumberChanging(value);
                ReportPropertyChanging("UnitNumber");
                _UnitNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitNumber");
                OnUnitNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _UnitNumber;
        partial void OnUnitNumberChanging(Nullable<global::System.Int32> value);
        partial void OnUnitNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PlannedStartDate
        {
            get
            {
                return _PlannedStartDate;
            }
            set
            {
                OnPlannedStartDateChanging(value);
                ReportPropertyChanging("PlannedStartDate");
                _PlannedStartDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlannedStartDate");
                OnPlannedStartDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PlannedStartDate;
        partial void OnPlannedStartDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPlannedStartDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PlannedEndDate
        {
            get
            {
                return _PlannedEndDate;
            }
            set
            {
                OnPlannedEndDateChanging(value);
                ReportPropertyChanging("PlannedEndDate");
                _PlannedEndDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlannedEndDate");
                OnPlannedEndDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PlannedEndDate;
        partial void OnPlannedEndDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPlannedEndDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PlannedChargeTime
        {
            get
            {
                return _PlannedChargeTime;
            }
            set
            {
                OnPlannedChargeTimeChanging(value);
                ReportPropertyChanging("PlannedChargeTime");
                _PlannedChargeTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlannedChargeTime");
                OnPlannedChargeTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PlannedChargeTime;
        partial void OnPlannedChargeTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPlannedChargeTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HNS
        {
            get
            {
                return _HNS;
            }
            set
            {
                OnHNSChanging(value);
                ReportPropertyChanging("HNS");
                _HNS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HNS");
                OnHNSChanged();
            }
        }
        private global::System.Int32 _HNS;
        partial void OnHNSChanging(global::System.Int32 value);
        partial void OnHNSChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ElvisDBModel", Name="CasterTotalsByShiftForDay")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class CasterTotalsByShiftForDay : ComplexObject
    {
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Shift
        {
            get
            {
                return _Shift;
            }
            set
            {
                OnShiftChanging(value);
                ReportPropertyChanging("Shift");
                _Shift = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Shift");
                OnShiftChanged();
            }
        }
        private global::System.String _Shift;
        partial void OnShiftChanging(global::System.String value);
        partial void OnShiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC1
        {
            get
            {
                return _CC1;
            }
            set
            {
                OnCC1Changing(value);
                ReportPropertyChanging("CC1");
                _CC1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1");
                OnCC1Changed();
            }
        }
        private Nullable<global::System.Int32> _CC1;
        partial void OnCC1Changing(Nullable<global::System.Int32> value);
        partial void OnCC1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC2
        {
            get
            {
                return _CC2;
            }
            set
            {
                OnCC2Changing(value);
                ReportPropertyChanging("CC2");
                _CC2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2");
                OnCC2Changed();
            }
        }
        private Nullable<global::System.Int32> _CC2;
        partial void OnCC2Changing(Nullable<global::System.Int32> value);
        partial void OnCC2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC3
        {
            get
            {
                return _CC3;
            }
            set
            {
                OnCC3Changing(value);
                ReportPropertyChanging("CC3");
                _CC3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3");
                OnCC3Changed();
            }
        }
        private Nullable<global::System.Int32> _CC3;
        partial void OnCC3Changing(Nullable<global::System.Int32> value);
        partial void OnCC3Changed();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ElvisDBModel", Name="CasterTotalsByShiftForWeek")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class CasterTotalsByShiftForWeek : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CasterTotalsByShiftForWeek object.
        /// </summary>
        /// <param name="tataDay">Initial value of the TataDay property.</param>
        /// <param name="shiftDate">Initial value of the ShiftDate property.</param>
        public static CasterTotalsByShiftForWeek CreateCasterTotalsByShiftForWeek(global::System.Byte tataDay, global::System.DateTime shiftDate)
        {
            CasterTotalsByShiftForWeek casterTotalsByShiftForWeek = new CasterTotalsByShiftForWeek();
            casterTotalsByShiftForWeek.TataDay = tataDay;
            casterTotalsByShiftForWeek.ShiftDate = shiftDate;
            return casterTotalsByShiftForWeek;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte TataDay
        {
            get
            {
                return _TataDay;
            }
            set
            {
                OnTataDayChanging(value);
                ReportPropertyChanging("TataDay");
                _TataDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TataDay");
                OnTataDayChanged();
            }
        }
        private global::System.Byte _TataDay;
        partial void OnTataDayChanging(global::System.Byte value);
        partial void OnTataDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Shift
        {
            get
            {
                return _Shift;
            }
            set
            {
                OnShiftChanging(value);
                ReportPropertyChanging("Shift");
                _Shift = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Shift");
                OnShiftChanged();
            }
        }
        private global::System.String _Shift;
        partial void OnShiftChanging(global::System.String value);
        partial void OnShiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC1
        {
            get
            {
                return _CC1;
            }
            set
            {
                OnCC1Changing(value);
                ReportPropertyChanging("CC1");
                _CC1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1");
                OnCC1Changed();
            }
        }
        private Nullable<global::System.Int32> _CC1;
        partial void OnCC1Changing(Nullable<global::System.Int32> value);
        partial void OnCC1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC2
        {
            get
            {
                return _CC2;
            }
            set
            {
                OnCC2Changing(value);
                ReportPropertyChanging("CC2");
                _CC2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2");
                OnCC2Changed();
            }
        }
        private Nullable<global::System.Int32> _CC2;
        partial void OnCC2Changing(Nullable<global::System.Int32> value);
        partial void OnCC2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC3
        {
            get
            {
                return _CC3;
            }
            set
            {
                OnCC3Changing(value);
                ReportPropertyChanging("CC3");
                _CC3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3");
                OnCC3Changed();
            }
        }
        private Nullable<global::System.Int32> _CC3;
        partial void OnCC3Changing(Nullable<global::System.Int32> value);
        partial void OnCC3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ShiftDate
        {
            get
            {
                return _ShiftDate;
            }
            set
            {
                OnShiftDateChanging(value);
                ReportPropertyChanging("ShiftDate");
                _ShiftDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShiftDate");
                OnShiftDateChanged();
            }
        }
        private global::System.DateTime _ShiftDate;
        partial void OnShiftDateChanging(global::System.DateTime value);
        partial void OnShiftDateChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ElvisDBModel", Name="ShiftStartHeatPlanItem")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ShiftStartHeatPlanItem : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShiftStartHeatPlanItem object.
        /// </summary>
        /// <param name="shift">Initial value of the Shift property.</param>
        /// <param name="heatNumber">Initial value of the HeatNumber property.</param>
        /// <param name="heatNumberSet">Initial value of the HeatNumberSet property.</param>
        public static ShiftStartHeatPlanItem CreateShiftStartHeatPlanItem(global::System.String shift, global::System.Int32 heatNumber, global::System.Int32 heatNumberSet)
        {
            ShiftStartHeatPlanItem shiftStartHeatPlanItem = new ShiftStartHeatPlanItem();
            shiftStartHeatPlanItem.Shift = shift;
            shiftStartHeatPlanItem.HeatNumber = heatNumber;
            shiftStartHeatPlanItem.HeatNumberSet = heatNumberSet;
            return shiftStartHeatPlanItem;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Shift
        {
            get
            {
                return _Shift;
            }
            set
            {
                OnShiftChanging(value);
                ReportPropertyChanging("Shift");
                _Shift = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Shift");
                OnShiftChanged();
            }
        }
        private global::System.String _Shift;
        partial void OnShiftChanging(global::System.String value);
        partial void OnShiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                OnHeatNumberChanging(value);
                ReportPropertyChanging("HeatNumber");
                _HeatNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeatNumber");
                OnHeatNumberChanged();
            }
        }
        private global::System.Int32 _HeatNumber;
        partial void OnHeatNumberChanging(global::System.Int32 value);
        partial void OnHeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeatNumberSet
        {
            get
            {
                return _HeatNumberSet;
            }
            set
            {
                OnHeatNumberSetChanging(value);
                ReportPropertyChanging("HeatNumberSet");
                _HeatNumberSet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeatNumberSet");
                OnHeatNumberSetChanged();
            }
        }
        private global::System.Int32 _HeatNumberSet;
        partial void OnHeatNumberSetChanging(global::System.Int32 value);
        partial void OnHeatNumberSetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> ProgramNumber
        {
            get
            {
                return _ProgramNumber;
            }
            set
            {
                OnProgramNumberChanging(value);
                ReportPropertyChanging("ProgramNumber");
                _ProgramNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramNumber");
                OnProgramNumberChanged();
            }
        }
        private Nullable<global::System.Int16> _ProgramNumber;
        partial void OnProgramNumberChanging(Nullable<global::System.Int16> value);
        partial void OnProgramNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Grade
        {
            get
            {
                return _Grade;
            }
            set
            {
                OnGradeChanging(value);
                ReportPropertyChanging("Grade");
                _Grade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Grade");
                OnGradeChanged();
            }
        }
        private Nullable<global::System.Int16> _Grade;
        partial void OnGradeChanging(Nullable<global::System.Int16> value);
        partial void OnGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> VesselNumber
        {
            get
            {
                return _VesselNumber;
            }
            set
            {
                OnVesselNumberChanging(value);
                ReportPropertyChanging("VesselNumber");
                _VesselNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VesselNumber");
                OnVesselNumberChanged();
            }
        }
        private Nullable<global::System.Int16> _VesselNumber;
        partial void OnVesselNumberChanging(Nullable<global::System.Int16> value);
        partial void OnVesselNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> CasterNumber
        {
            get
            {
                return _CasterNumber;
            }
            set
            {
                OnCasterNumberChanging(value);
                ReportPropertyChanging("CasterNumber");
                _CasterNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CasterNumber");
                OnCasterNumberChanged();
            }
        }
        private Nullable<global::System.Int16> _CasterNumber;
        partial void OnCasterNumberChanging(Nullable<global::System.Int16> value);
        partial void OnCasterNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PlannedEndCastTime
        {
            get
            {
                return _PlannedEndCastTime;
            }
            set
            {
                OnPlannedEndCastTimeChanging(value);
                ReportPropertyChanging("PlannedEndCastTime");
                _PlannedEndCastTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlannedEndCastTime");
                OnPlannedEndCastTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PlannedEndCastTime;
        partial void OnPlannedEndCastTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPlannedEndCastTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PlannedStartCastTime
        {
            get
            {
                return _PlannedStartCastTime;
            }
            set
            {
                OnPlannedStartCastTimeChanging(value);
                ReportPropertyChanging("PlannedStartCastTime");
                _PlannedStartCastTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlannedStartCastTime");
                OnPlannedStartCastTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _PlannedStartCastTime;
        partial void OnPlannedStartCastTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnPlannedStartCastTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> CombinedWidth
        {
            get
            {
                return _CombinedWidth;
            }
            set
            {
                OnCombinedWidthChanging(value);
                ReportPropertyChanging("CombinedWidth");
                _CombinedWidth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CombinedWidth");
                OnCombinedWidthChanged();
            }
        }
        private Nullable<global::System.Int16> _CombinedWidth;
        partial void OnCombinedWidthChanging(Nullable<global::System.Int16> value);
        partial void OnCombinedWidthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> Duration
        {
            get
            {
                return _Duration;
            }
            set
            {
                OnDurationChanging(value);
                ReportPropertyChanging("Duration");
                _Duration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Duration");
                OnDurationChanged();
            }
        }
        private Nullable<global::System.Int16> _Duration;
        partial void OnDurationChanging(Nullable<global::System.Int16> value);
        partial void OnDurationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> UpdateTime
        {
            get
            {
                return _UpdateTime;
            }
            set
            {
                OnUpdateTimeChanging(value);
                ReportPropertyChanging("UpdateTime");
                _UpdateTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UpdateTime");
                OnUpdateTimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _UpdateTime;
        partial void OnUpdateTimeChanging(Nullable<global::System.DateTime> value);
        partial void OnUpdateTimeChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="ElvisDBModel", Name="TodayDate")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class TodayDate : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TodayDate object.
        /// </summary>
        /// <param name="currentYear">Initial value of the CurrentYear property.</param>
        /// <param name="currentWeek">Initial value of the CurrentWeek property.</param>
        /// <param name="currentDay">Initial value of the CurrentDay property.</param>
        /// <param name="currentRota">Initial value of the CurrentRota property.</param>
        /// <param name="currentShift">Initial value of the CurrentShift property.</param>
        /// <param name="currentShiftNumber">Initial value of the CurrentShiftNumber property.</param>
        public static TodayDate CreateTodayDate(global::System.Int16 currentYear, global::System.Byte currentWeek, global::System.Byte currentDay, global::System.String currentRota, global::System.String currentShift, global::System.Int32 currentShiftNumber)
        {
            TodayDate todayDate = new TodayDate();
            todayDate.CurrentYear = currentYear;
            todayDate.CurrentWeek = currentWeek;
            todayDate.CurrentDay = currentDay;
            todayDate.CurrentRota = currentRota;
            todayDate.CurrentShift = currentShift;
            todayDate.CurrentShiftNumber = currentShiftNumber;
            return todayDate;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 CurrentYear
        {
            get
            {
                return _CurrentYear;
            }
            set
            {
                OnCurrentYearChanging(value);
                ReportPropertyChanging("CurrentYear");
                _CurrentYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentYear");
                OnCurrentYearChanged();
            }
        }
        private global::System.Int16 _CurrentYear;
        partial void OnCurrentYearChanging(global::System.Int16 value);
        partial void OnCurrentYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CurrentWeek
        {
            get
            {
                return _CurrentWeek;
            }
            set
            {
                OnCurrentWeekChanging(value);
                ReportPropertyChanging("CurrentWeek");
                _CurrentWeek = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentWeek");
                OnCurrentWeekChanged();
            }
        }
        private global::System.Byte _CurrentWeek;
        partial void OnCurrentWeekChanging(global::System.Byte value);
        partial void OnCurrentWeekChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte CurrentDay
        {
            get
            {
                return _CurrentDay;
            }
            set
            {
                OnCurrentDayChanging(value);
                ReportPropertyChanging("CurrentDay");
                _CurrentDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentDay");
                OnCurrentDayChanged();
            }
        }
        private global::System.Byte _CurrentDay;
        partial void OnCurrentDayChanging(global::System.Byte value);
        partial void OnCurrentDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CurrentRota
        {
            get
            {
                return _CurrentRota;
            }
            set
            {
                OnCurrentRotaChanging(value);
                ReportPropertyChanging("CurrentRota");
                _CurrentRota = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CurrentRota");
                OnCurrentRotaChanged();
            }
        }
        private global::System.String _CurrentRota;
        partial void OnCurrentRotaChanging(global::System.String value);
        partial void OnCurrentRotaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartDay
        {
            get
            {
                return _StartDay;
            }
            set
            {
                OnStartDayChanging(value);
                ReportPropertyChanging("StartDay");
                _StartDay = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartDay");
                OnStartDayChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartDay;
        partial void OnStartDayChanging(Nullable<global::System.DateTime> value);
        partial void OnStartDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> StartShift
        {
            get
            {
                return _StartShift;
            }
            set
            {
                OnStartShiftChanging(value);
                ReportPropertyChanging("StartShift");
                _StartShift = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StartShift");
                OnStartShiftChanged();
            }
        }
        private Nullable<global::System.DateTime> _StartShift;
        partial void OnStartShiftChanging(Nullable<global::System.DateTime> value);
        partial void OnStartShiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CurrentShift
        {
            get
            {
                return _CurrentShift;
            }
            set
            {
                OnCurrentShiftChanging(value);
                ReportPropertyChanging("CurrentShift");
                _CurrentShift = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CurrentShift");
                OnCurrentShiftChanged();
            }
        }
        private global::System.String _CurrentShift;
        partial void OnCurrentShiftChanging(global::System.String value);
        partial void OnCurrentShiftChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CurrentShiftNumber
        {
            get
            {
                return _CurrentShiftNumber;
            }
            set
            {
                OnCurrentShiftNumberChanging(value);
                ReportPropertyChanging("CurrentShiftNumber");
                _CurrentShiftNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentShiftNumber");
                OnCurrentShiftNumberChanged();
            }
        }
        private global::System.Int32 _CurrentShiftNumber;
        partial void OnCurrentShiftNumberChanging(global::System.Int32 value);
        partial void OnCurrentShiftNumberChanged();

        #endregion

    }

    #endregion

    
}
