//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ElvisDataModel.EDMX
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OasisSchemaEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OasisSchemaEntities object using the connection string found in the 'OasisSchemaEntities' section of the application configuration file.
        /// </summary>
        public OasisSchemaEntities() : base("name=OasisSchemaEntities", "OasisSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OasisSchemaEntities object.
        /// </summary>
        public OasisSchemaEntities(string connectionString) : base(connectionString, "OasisSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OasisSchemaEntities object.
        /// </summary>
        public OasisSchemaEntities(EntityConnection connection) : base(connection, "OasisSchemaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<RFTData> RFTDatas
        {
            get
            {
                if ((_RFTDatas == null))
                {
                    _RFTDatas = base.CreateObjectSet<RFTData>("RFTDatas");
                }
                return _RFTDatas;
            }
        }
        private ObjectSet<RFTData> _RFTDatas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SlabStock> SlabStocks
        {
            get
            {
                if ((_SlabStocks == null))
                {
                    _SlabStocks = base.CreateObjectSet<SlabStock>("SlabStocks");
                }
                return _SlabStocks;
            }
        }
        private ObjectSet<SlabStock> _SlabStocks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HotConnect> HotConnects
        {
            get
            {
                if ((_HotConnects == null))
                {
                    _HotConnects = base.CreateObjectSet<HotConnect>("HotConnects");
                }
                return _HotConnects;
            }
        }
        private ObjectSet<HotConnect> _HotConnects;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the RFTDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRFTDatas(RFTData rFTData)
        {
            base.AddObject("RFTDatas", rFTData);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SlabStocks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSlabStocks(SlabStock slabStock)
        {
            base.AddObject("SlabStocks", slabStock);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the HotConnects EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHotConnects(HotConnect hotConnect)
        {
            base.AddObject("HotConnects", hotConnect);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OasisSchema", Name="HotConnect")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HotConnect : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HotConnect object.
        /// </summary>
        /// <param name="hCId">Initial value of the HCId property.</param>
        public static HotConnect CreateHotConnect(global::System.Int32 hCId)
        {
            HotConnect hotConnect = new HotConnect();
            hotConnect.HCId = hCId;
            return hotConnect;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HCId
        {
            get
            {
                return _HCId;
            }
            set
            {
                if (_HCId != value)
                {
                    OnHCIdChanging(value);
                    ReportPropertyChanging("HCId");
                    _HCId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("HCId");
                    OnHCIdChanged();
                }
            }
        }
        private global::System.Int32 _HCId;
        partial void OnHCIdChanging(global::System.Int32 value);
        partial void OnHCIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HeatNumber
        {
            get
            {
                return _HeatNumber;
            }
            set
            {
                OnHeatNumberChanging(value);
                ReportPropertyChanging("HeatNumber");
                _HeatNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeatNumber");
                OnHeatNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _HeatNumber;
        partial void OnHeatNumberChanging(Nullable<global::System.Int32> value);
        partial void OnHeatNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HNS
        {
            get
            {
                return _HNS;
            }
            set
            {
                OnHNSChanging(value);
                ReportPropertyChanging("HNS");
                _HNS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HNS");
                OnHNSChanged();
            }
        }
        private Nullable<global::System.Int32> _HNS;
        partial void OnHNSChanging(Nullable<global::System.Int32> value);
        partial void OnHNSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ProgramNumber
        {
            get
            {
                return _ProgramNumber;
            }
            set
            {
                OnProgramNumberChanging(value);
                ReportPropertyChanging("ProgramNumber");
                _ProgramNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProgramNumber");
                OnProgramNumberChanged();
            }
        }
        private Nullable<global::System.Int32> _ProgramNumber;
        partial void OnProgramNumberChanging(Nullable<global::System.Int32> value);
        partial void OnProgramNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HotConnectFlag
        {
            get
            {
                return _HotConnectFlag;
            }
            set
            {
                OnHotConnectFlagChanging(value);
                ReportPropertyChanging("HotConnectFlag");
                _HotConnectFlag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HotConnectFlag");
                OnHotConnectFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _HotConnectFlag;
        partial void OnHotConnectFlagChanging(Nullable<global::System.Int32> value);
        partial void OnHotConnectFlagChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastUpdate
        {
            get
            {
                return _LastUpdate;
            }
            set
            {
                OnLastUpdateChanging(value);
                ReportPropertyChanging("LastUpdate");
                _LastUpdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdate");
                OnLastUpdateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastUpdate;
        partial void OnLastUpdateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastUpdateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OasisSchema", Name="RFTData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class RFTData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new RFTData object.
        /// </summary>
        /// <param name="rFTIndex">Initial value of the RFTIndex property.</param>
        public static RFTData CreateRFTData(global::System.Int32 rFTIndex)
        {
            RFTData rFTData = new RFTData();
            rFTData.RFTIndex = rFTIndex;
            return rFTData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RFTIndex
        {
            get
            {
                return _RFTIndex;
            }
            set
            {
                if (_RFTIndex != value)
                {
                    OnRFTIndexChanging(value);
                    ReportPropertyChanging("RFTIndex");
                    _RFTIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RFTIndex");
                    OnRFTIndexChanged();
                }
            }
        }
        private global::System.Int32 _RFTIndex;
        partial void OnRFTIndexChanging(global::System.Int32 value);
        partial void OnRFTIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RFTDate
        {
            get
            {
                return _RFTDate;
            }
            set
            {
                OnRFTDateChanging(value);
                ReportPropertyChanging("RFTDate");
                _RFTDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RFTDate");
                OnRFTDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RFTDate;
        partial void OnRFTDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRFTDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SlabsMade
        {
            get
            {
                return _SlabsMade;
            }
            set
            {
                OnSlabsMadeChanging(value);
                ReportPropertyChanging("SlabsMade");
                _SlabsMade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlabsMade");
                OnSlabsMadeChanged();
            }
        }
        private Nullable<global::System.Int32> _SlabsMade;
        partial void OnSlabsMadeChanging(Nullable<global::System.Int32> value);
        partial void OnSlabsMadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SlabsMadeSchedule
        {
            get
            {
                return _SlabsMadeSchedule;
            }
            set
            {
                OnSlabsMadeScheduleChanging(value);
                ReportPropertyChanging("SlabsMadeSchedule");
                _SlabsMadeSchedule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlabsMadeSchedule");
                OnSlabsMadeScheduleChanged();
            }
        }
        private Nullable<global::System.Int32> _SlabsMadeSchedule;
        partial void OnSlabsMadeScheduleChanging(Nullable<global::System.Int32> value);
        partial void OnSlabsMadeScheduleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ShedGradeOk
        {
            get
            {
                return _ShedGradeOk;
            }
            set
            {
                OnShedGradeOkChanging(value);
                ReportPropertyChanging("ShedGradeOk");
                _ShedGradeOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShedGradeOk");
                OnShedGradeOkChanged();
            }
        }
        private Nullable<global::System.Int32> _ShedGradeOk;
        partial void OnShedGradeOkChanging(Nullable<global::System.Int32> value);
        partial void OnShedGradeOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ShedWidthOk
        {
            get
            {
                return _ShedWidthOk;
            }
            set
            {
                OnShedWidthOkChanging(value);
                ReportPropertyChanging("ShedWidthOk");
                _ShedWidthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShedWidthOk");
                OnShedWidthOkChanged();
            }
        }
        private Nullable<global::System.Int32> _ShedWidthOk;
        partial void OnShedWidthOkChanging(Nullable<global::System.Int32> value);
        partial void OnShedWidthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ShedLengthOk
        {
            get
            {
                return _ShedLengthOk;
            }
            set
            {
                OnShedLengthOkChanging(value);
                ReportPropertyChanging("ShedLengthOk");
                _ShedLengthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShedLengthOk");
                OnShedLengthOkChanged();
            }
        }
        private Nullable<global::System.Int32> _ShedLengthOk;
        partial void OnShedLengthOkChanging(Nullable<global::System.Int32> value);
        partial void OnShedLengthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SlabsRFT
        {
            get
            {
                return _SlabsRFT;
            }
            set
            {
                OnSlabsRFTChanging(value);
                ReportPropertyChanging("SlabsRFT");
                _SlabsRFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlabsRFT");
                OnSlabsRFTChanged();
            }
        }
        private Nullable<global::System.Int32> _SlabsRFT;
        partial void OnSlabsRFTChanging(Nullable<global::System.Int32> value);
        partial void OnSlabsRFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SlabsAppliedTGrade
        {
            get
            {
                return _SlabsAppliedTGrade;
            }
            set
            {
                OnSlabsAppliedTGradeChanging(value);
                ReportPropertyChanging("SlabsAppliedTGrade");
                _SlabsAppliedTGrade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SlabsAppliedTGrade");
                OnSlabsAppliedTGradeChanged();
            }
        }
        private Nullable<global::System.Int32> _SlabsAppliedTGrade;
        partial void OnSlabsAppliedTGradeChanging(Nullable<global::System.Int32> value);
        partial void OnSlabsAppliedTGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> TonnesMade
        {
            get
            {
                return _TonnesMade;
            }
            set
            {
                OnTonnesMadeChanging(value);
                ReportPropertyChanging("TonnesMade");
                _TonnesMade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TonnesMade");
                OnTonnesMadeChanged();
            }
        }
        private Nullable<global::System.Single> _TonnesMade;
        partial void OnTonnesMadeChanging(Nullable<global::System.Single> value);
        partial void OnTonnesMadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> TonnesMadeSchedule
        {
            get
            {
                return _TonnesMadeSchedule;
            }
            set
            {
                OnTonnesMadeScheduleChanging(value);
                ReportPropertyChanging("TonnesMadeSchedule");
                _TonnesMadeSchedule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TonnesMadeSchedule");
                OnTonnesMadeScheduleChanged();
            }
        }
        private Nullable<global::System.Single> _TonnesMadeSchedule;
        partial void OnTonnesMadeScheduleChanging(Nullable<global::System.Single> value);
        partial void OnTonnesMadeScheduleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> TonnesGradeOk
        {
            get
            {
                return _TonnesGradeOk;
            }
            set
            {
                OnTonnesGradeOkChanging(value);
                ReportPropertyChanging("TonnesGradeOk");
                _TonnesGradeOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TonnesGradeOk");
                OnTonnesGradeOkChanged();
            }
        }
        private Nullable<global::System.Single> _TonnesGradeOk;
        partial void OnTonnesGradeOkChanging(Nullable<global::System.Single> value);
        partial void OnTonnesGradeOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> TonnesWidthOk
        {
            get
            {
                return _TonnesWidthOk;
            }
            set
            {
                OnTonnesWidthOkChanging(value);
                ReportPropertyChanging("TonnesWidthOk");
                _TonnesWidthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TonnesWidthOk");
                OnTonnesWidthOkChanged();
            }
        }
        private Nullable<global::System.Single> _TonnesWidthOk;
        partial void OnTonnesWidthOkChanging(Nullable<global::System.Single> value);
        partial void OnTonnesWidthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> TonnesLengthOk
        {
            get
            {
                return _TonnesLengthOk;
            }
            set
            {
                OnTonnesLengthOkChanging(value);
                ReportPropertyChanging("TonnesLengthOk");
                _TonnesLengthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TonnesLengthOk");
                OnTonnesLengthOkChanged();
            }
        }
        private Nullable<global::System.Single> _TonnesLengthOk;
        partial void OnTonnesLengthOkChanging(Nullable<global::System.Single> value);
        partial void OnTonnesLengthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> TonnesRFT
        {
            get
            {
                return _TonnesRFT;
            }
            set
            {
                OnTonnesRFTChanging(value);
                ReportPropertyChanging("TonnesRFT");
                _TonnesRFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TonnesRFT");
                OnTonnesRFTChanged();
            }
        }
        private Nullable<global::System.Single> _TonnesRFT;
        partial void OnTonnesRFTChanging(Nullable<global::System.Single> value);
        partial void OnTonnesRFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> TonnesAppliedTGrade
        {
            get
            {
                return _TonnesAppliedTGrade;
            }
            set
            {
                OnTonnesAppliedTGradeChanging(value);
                ReportPropertyChanging("TonnesAppliedTGrade");
                _TonnesAppliedTGrade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TonnesAppliedTGrade");
                OnTonnesAppliedTGradeChanged();
            }
        }
        private Nullable<global::System.Single> _TonnesAppliedTGrade;
        partial void OnTonnesAppliedTGradeChanging(Nullable<global::System.Single> value);
        partial void OnTonnesAppliedTGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC1SlabsMade
        {
            get
            {
                return _CC1SlabsMade;
            }
            set
            {
                OnCC1SlabsMadeChanging(value);
                ReportPropertyChanging("CC1SlabsMade");
                _CC1SlabsMade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1SlabsMade");
                OnCC1SlabsMadeChanged();
            }
        }
        private Nullable<global::System.Int32> _CC1SlabsMade;
        partial void OnCC1SlabsMadeChanging(Nullable<global::System.Int32> value);
        partial void OnCC1SlabsMadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC1SlabsMadeSchedule
        {
            get
            {
                return _CC1SlabsMadeSchedule;
            }
            set
            {
                OnCC1SlabsMadeScheduleChanging(value);
                ReportPropertyChanging("CC1SlabsMadeSchedule");
                _CC1SlabsMadeSchedule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1SlabsMadeSchedule");
                OnCC1SlabsMadeScheduleChanged();
            }
        }
        private Nullable<global::System.Int32> _CC1SlabsMadeSchedule;
        partial void OnCC1SlabsMadeScheduleChanging(Nullable<global::System.Int32> value);
        partial void OnCC1SlabsMadeScheduleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC1ShedGradeOk
        {
            get
            {
                return _CC1ShedGradeOk;
            }
            set
            {
                OnCC1ShedGradeOkChanging(value);
                ReportPropertyChanging("CC1ShedGradeOk");
                _CC1ShedGradeOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1ShedGradeOk");
                OnCC1ShedGradeOkChanged();
            }
        }
        private Nullable<global::System.Int32> _CC1ShedGradeOk;
        partial void OnCC1ShedGradeOkChanging(Nullable<global::System.Int32> value);
        partial void OnCC1ShedGradeOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC1ShedWidthOk
        {
            get
            {
                return _CC1ShedWidthOk;
            }
            set
            {
                OnCC1ShedWidthOkChanging(value);
                ReportPropertyChanging("CC1ShedWidthOk");
                _CC1ShedWidthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1ShedWidthOk");
                OnCC1ShedWidthOkChanged();
            }
        }
        private Nullable<global::System.Int32> _CC1ShedWidthOk;
        partial void OnCC1ShedWidthOkChanging(Nullable<global::System.Int32> value);
        partial void OnCC1ShedWidthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC1ShedLengthOk
        {
            get
            {
                return _CC1ShedLengthOk;
            }
            set
            {
                OnCC1ShedLengthOkChanging(value);
                ReportPropertyChanging("CC1ShedLengthOk");
                _CC1ShedLengthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1ShedLengthOk");
                OnCC1ShedLengthOkChanged();
            }
        }
        private Nullable<global::System.Int32> _CC1ShedLengthOk;
        partial void OnCC1ShedLengthOkChanging(Nullable<global::System.Int32> value);
        partial void OnCC1ShedLengthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC1SlabsRFT
        {
            get
            {
                return _CC1SlabsRFT;
            }
            set
            {
                OnCC1SlabsRFTChanging(value);
                ReportPropertyChanging("CC1SlabsRFT");
                _CC1SlabsRFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1SlabsRFT");
                OnCC1SlabsRFTChanged();
            }
        }
        private Nullable<global::System.Int32> _CC1SlabsRFT;
        partial void OnCC1SlabsRFTChanging(Nullable<global::System.Int32> value);
        partial void OnCC1SlabsRFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC1SlabsAppliedTGrade
        {
            get
            {
                return _CC1SlabsAppliedTGrade;
            }
            set
            {
                OnCC1SlabsAppliedTGradeChanging(value);
                ReportPropertyChanging("CC1SlabsAppliedTGrade");
                _CC1SlabsAppliedTGrade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1SlabsAppliedTGrade");
                OnCC1SlabsAppliedTGradeChanged();
            }
        }
        private Nullable<global::System.Int32> _CC1SlabsAppliedTGrade;
        partial void OnCC1SlabsAppliedTGradeChanging(Nullable<global::System.Int32> value);
        partial void OnCC1SlabsAppliedTGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC1TonnesMade
        {
            get
            {
                return _CC1TonnesMade;
            }
            set
            {
                OnCC1TonnesMadeChanging(value);
                ReportPropertyChanging("CC1TonnesMade");
                _CC1TonnesMade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1TonnesMade");
                OnCC1TonnesMadeChanged();
            }
        }
        private Nullable<global::System.Single> _CC1TonnesMade;
        partial void OnCC1TonnesMadeChanging(Nullable<global::System.Single> value);
        partial void OnCC1TonnesMadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC1TonnesMadeSchedule
        {
            get
            {
                return _CC1TonnesMadeSchedule;
            }
            set
            {
                OnCC1TonnesMadeScheduleChanging(value);
                ReportPropertyChanging("CC1TonnesMadeSchedule");
                _CC1TonnesMadeSchedule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1TonnesMadeSchedule");
                OnCC1TonnesMadeScheduleChanged();
            }
        }
        private Nullable<global::System.Single> _CC1TonnesMadeSchedule;
        partial void OnCC1TonnesMadeScheduleChanging(Nullable<global::System.Single> value);
        partial void OnCC1TonnesMadeScheduleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC1TonnesGradeOk
        {
            get
            {
                return _CC1TonnesGradeOk;
            }
            set
            {
                OnCC1TonnesGradeOkChanging(value);
                ReportPropertyChanging("CC1TonnesGradeOk");
                _CC1TonnesGradeOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1TonnesGradeOk");
                OnCC1TonnesGradeOkChanged();
            }
        }
        private Nullable<global::System.Single> _CC1TonnesGradeOk;
        partial void OnCC1TonnesGradeOkChanging(Nullable<global::System.Single> value);
        partial void OnCC1TonnesGradeOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC1TonnesWidthOk
        {
            get
            {
                return _CC1TonnesWidthOk;
            }
            set
            {
                OnCC1TonnesWidthOkChanging(value);
                ReportPropertyChanging("CC1TonnesWidthOk");
                _CC1TonnesWidthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1TonnesWidthOk");
                OnCC1TonnesWidthOkChanged();
            }
        }
        private Nullable<global::System.Single> _CC1TonnesWidthOk;
        partial void OnCC1TonnesWidthOkChanging(Nullable<global::System.Single> value);
        partial void OnCC1TonnesWidthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC1TonnesLengthOk
        {
            get
            {
                return _CC1TonnesLengthOk;
            }
            set
            {
                OnCC1TonnesLengthOkChanging(value);
                ReportPropertyChanging("CC1TonnesLengthOk");
                _CC1TonnesLengthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1TonnesLengthOk");
                OnCC1TonnesLengthOkChanged();
            }
        }
        private Nullable<global::System.Single> _CC1TonnesLengthOk;
        partial void OnCC1TonnesLengthOkChanging(Nullable<global::System.Single> value);
        partial void OnCC1TonnesLengthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC1TonnesRFT
        {
            get
            {
                return _CC1TonnesRFT;
            }
            set
            {
                OnCC1TonnesRFTChanging(value);
                ReportPropertyChanging("CC1TonnesRFT");
                _CC1TonnesRFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1TonnesRFT");
                OnCC1TonnesRFTChanged();
            }
        }
        private Nullable<global::System.Single> _CC1TonnesRFT;
        partial void OnCC1TonnesRFTChanging(Nullable<global::System.Single> value);
        partial void OnCC1TonnesRFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC1TonnesAppliedTGrade
        {
            get
            {
                return _CC1TonnesAppliedTGrade;
            }
            set
            {
                OnCC1TonnesAppliedTGradeChanging(value);
                ReportPropertyChanging("CC1TonnesAppliedTGrade");
                _CC1TonnesAppliedTGrade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC1TonnesAppliedTGrade");
                OnCC1TonnesAppliedTGradeChanged();
            }
        }
        private Nullable<global::System.Single> _CC1TonnesAppliedTGrade;
        partial void OnCC1TonnesAppliedTGradeChanging(Nullable<global::System.Single> value);
        partial void OnCC1TonnesAppliedTGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC2SlabsMade
        {
            get
            {
                return _CC2SlabsMade;
            }
            set
            {
                OnCC2SlabsMadeChanging(value);
                ReportPropertyChanging("CC2SlabsMade");
                _CC2SlabsMade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2SlabsMade");
                OnCC2SlabsMadeChanged();
            }
        }
        private Nullable<global::System.Int32> _CC2SlabsMade;
        partial void OnCC2SlabsMadeChanging(Nullable<global::System.Int32> value);
        partial void OnCC2SlabsMadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC2SlabsMadeSchedule
        {
            get
            {
                return _CC2SlabsMadeSchedule;
            }
            set
            {
                OnCC2SlabsMadeScheduleChanging(value);
                ReportPropertyChanging("CC2SlabsMadeSchedule");
                _CC2SlabsMadeSchedule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2SlabsMadeSchedule");
                OnCC2SlabsMadeScheduleChanged();
            }
        }
        private Nullable<global::System.Int32> _CC2SlabsMadeSchedule;
        partial void OnCC2SlabsMadeScheduleChanging(Nullable<global::System.Int32> value);
        partial void OnCC2SlabsMadeScheduleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC2ShedGradeOk
        {
            get
            {
                return _CC2ShedGradeOk;
            }
            set
            {
                OnCC2ShedGradeOkChanging(value);
                ReportPropertyChanging("CC2ShedGradeOk");
                _CC2ShedGradeOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2ShedGradeOk");
                OnCC2ShedGradeOkChanged();
            }
        }
        private Nullable<global::System.Int32> _CC2ShedGradeOk;
        partial void OnCC2ShedGradeOkChanging(Nullable<global::System.Int32> value);
        partial void OnCC2ShedGradeOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC2ShedWidthOk
        {
            get
            {
                return _CC2ShedWidthOk;
            }
            set
            {
                OnCC2ShedWidthOkChanging(value);
                ReportPropertyChanging("CC2ShedWidthOk");
                _CC2ShedWidthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2ShedWidthOk");
                OnCC2ShedWidthOkChanged();
            }
        }
        private Nullable<global::System.Int32> _CC2ShedWidthOk;
        partial void OnCC2ShedWidthOkChanging(Nullable<global::System.Int32> value);
        partial void OnCC2ShedWidthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC2ShedLengthOk
        {
            get
            {
                return _CC2ShedLengthOk;
            }
            set
            {
                OnCC2ShedLengthOkChanging(value);
                ReportPropertyChanging("CC2ShedLengthOk");
                _CC2ShedLengthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2ShedLengthOk");
                OnCC2ShedLengthOkChanged();
            }
        }
        private Nullable<global::System.Int32> _CC2ShedLengthOk;
        partial void OnCC2ShedLengthOkChanging(Nullable<global::System.Int32> value);
        partial void OnCC2ShedLengthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC2SlabsRFT
        {
            get
            {
                return _CC2SlabsRFT;
            }
            set
            {
                OnCC2SlabsRFTChanging(value);
                ReportPropertyChanging("CC2SlabsRFT");
                _CC2SlabsRFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2SlabsRFT");
                OnCC2SlabsRFTChanged();
            }
        }
        private Nullable<global::System.Int32> _CC2SlabsRFT;
        partial void OnCC2SlabsRFTChanging(Nullable<global::System.Int32> value);
        partial void OnCC2SlabsRFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC2SlabsAppliedTGrade
        {
            get
            {
                return _CC2SlabsAppliedTGrade;
            }
            set
            {
                OnCC2SlabsAppliedTGradeChanging(value);
                ReportPropertyChanging("CC2SlabsAppliedTGrade");
                _CC2SlabsAppliedTGrade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2SlabsAppliedTGrade");
                OnCC2SlabsAppliedTGradeChanged();
            }
        }
        private Nullable<global::System.Int32> _CC2SlabsAppliedTGrade;
        partial void OnCC2SlabsAppliedTGradeChanging(Nullable<global::System.Int32> value);
        partial void OnCC2SlabsAppliedTGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC2TonnesMade
        {
            get
            {
                return _CC2TonnesMade;
            }
            set
            {
                OnCC2TonnesMadeChanging(value);
                ReportPropertyChanging("CC2TonnesMade");
                _CC2TonnesMade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2TonnesMade");
                OnCC2TonnesMadeChanged();
            }
        }
        private Nullable<global::System.Single> _CC2TonnesMade;
        partial void OnCC2TonnesMadeChanging(Nullable<global::System.Single> value);
        partial void OnCC2TonnesMadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC2TonnesMadeSchedule
        {
            get
            {
                return _CC2TonnesMadeSchedule;
            }
            set
            {
                OnCC2TonnesMadeScheduleChanging(value);
                ReportPropertyChanging("CC2TonnesMadeSchedule");
                _CC2TonnesMadeSchedule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2TonnesMadeSchedule");
                OnCC2TonnesMadeScheduleChanged();
            }
        }
        private Nullable<global::System.Single> _CC2TonnesMadeSchedule;
        partial void OnCC2TonnesMadeScheduleChanging(Nullable<global::System.Single> value);
        partial void OnCC2TonnesMadeScheduleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC2TonnesGradeOk
        {
            get
            {
                return _CC2TonnesGradeOk;
            }
            set
            {
                OnCC2TonnesGradeOkChanging(value);
                ReportPropertyChanging("CC2TonnesGradeOk");
                _CC2TonnesGradeOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2TonnesGradeOk");
                OnCC2TonnesGradeOkChanged();
            }
        }
        private Nullable<global::System.Single> _CC2TonnesGradeOk;
        partial void OnCC2TonnesGradeOkChanging(Nullable<global::System.Single> value);
        partial void OnCC2TonnesGradeOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC2TonnesWidthOk
        {
            get
            {
                return _CC2TonnesWidthOk;
            }
            set
            {
                OnCC2TonnesWidthOkChanging(value);
                ReportPropertyChanging("CC2TonnesWidthOk");
                _CC2TonnesWidthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2TonnesWidthOk");
                OnCC2TonnesWidthOkChanged();
            }
        }
        private Nullable<global::System.Single> _CC2TonnesWidthOk;
        partial void OnCC2TonnesWidthOkChanging(Nullable<global::System.Single> value);
        partial void OnCC2TonnesWidthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC2TonnesLengthOk
        {
            get
            {
                return _CC2TonnesLengthOk;
            }
            set
            {
                OnCC2TonnesLengthOkChanging(value);
                ReportPropertyChanging("CC2TonnesLengthOk");
                _CC2TonnesLengthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2TonnesLengthOk");
                OnCC2TonnesLengthOkChanged();
            }
        }
        private Nullable<global::System.Single> _CC2TonnesLengthOk;
        partial void OnCC2TonnesLengthOkChanging(Nullable<global::System.Single> value);
        partial void OnCC2TonnesLengthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC2TonnesRFT
        {
            get
            {
                return _CC2TonnesRFT;
            }
            set
            {
                OnCC2TonnesRFTChanging(value);
                ReportPropertyChanging("CC2TonnesRFT");
                _CC2TonnesRFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2TonnesRFT");
                OnCC2TonnesRFTChanged();
            }
        }
        private Nullable<global::System.Single> _CC2TonnesRFT;
        partial void OnCC2TonnesRFTChanging(Nullable<global::System.Single> value);
        partial void OnCC2TonnesRFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC2TonnesAppliedTGrade
        {
            get
            {
                return _CC2TonnesAppliedTGrade;
            }
            set
            {
                OnCC2TonnesAppliedTGradeChanging(value);
                ReportPropertyChanging("CC2TonnesAppliedTGrade");
                _CC2TonnesAppliedTGrade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC2TonnesAppliedTGrade");
                OnCC2TonnesAppliedTGradeChanged();
            }
        }
        private Nullable<global::System.Single> _CC2TonnesAppliedTGrade;
        partial void OnCC2TonnesAppliedTGradeChanging(Nullable<global::System.Single> value);
        partial void OnCC2TonnesAppliedTGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC3SlabsMade
        {
            get
            {
                return _CC3SlabsMade;
            }
            set
            {
                OnCC3SlabsMadeChanging(value);
                ReportPropertyChanging("CC3SlabsMade");
                _CC3SlabsMade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3SlabsMade");
                OnCC3SlabsMadeChanged();
            }
        }
        private Nullable<global::System.Int32> _CC3SlabsMade;
        partial void OnCC3SlabsMadeChanging(Nullable<global::System.Int32> value);
        partial void OnCC3SlabsMadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC3SlabsMadeSchedule
        {
            get
            {
                return _CC3SlabsMadeSchedule;
            }
            set
            {
                OnCC3SlabsMadeScheduleChanging(value);
                ReportPropertyChanging("CC3SlabsMadeSchedule");
                _CC3SlabsMadeSchedule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3SlabsMadeSchedule");
                OnCC3SlabsMadeScheduleChanged();
            }
        }
        private Nullable<global::System.Int32> _CC3SlabsMadeSchedule;
        partial void OnCC3SlabsMadeScheduleChanging(Nullable<global::System.Int32> value);
        partial void OnCC3SlabsMadeScheduleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC3ShedGradeOk
        {
            get
            {
                return _CC3ShedGradeOk;
            }
            set
            {
                OnCC3ShedGradeOkChanging(value);
                ReportPropertyChanging("CC3ShedGradeOk");
                _CC3ShedGradeOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3ShedGradeOk");
                OnCC3ShedGradeOkChanged();
            }
        }
        private Nullable<global::System.Int32> _CC3ShedGradeOk;
        partial void OnCC3ShedGradeOkChanging(Nullable<global::System.Int32> value);
        partial void OnCC3ShedGradeOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC3ShedWidthOk
        {
            get
            {
                return _CC3ShedWidthOk;
            }
            set
            {
                OnCC3ShedWidthOkChanging(value);
                ReportPropertyChanging("CC3ShedWidthOk");
                _CC3ShedWidthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3ShedWidthOk");
                OnCC3ShedWidthOkChanged();
            }
        }
        private Nullable<global::System.Int32> _CC3ShedWidthOk;
        partial void OnCC3ShedWidthOkChanging(Nullable<global::System.Int32> value);
        partial void OnCC3ShedWidthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC3ShedLengthOk
        {
            get
            {
                return _CC3ShedLengthOk;
            }
            set
            {
                OnCC3ShedLengthOkChanging(value);
                ReportPropertyChanging("CC3ShedLengthOk");
                _CC3ShedLengthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3ShedLengthOk");
                OnCC3ShedLengthOkChanged();
            }
        }
        private Nullable<global::System.Int32> _CC3ShedLengthOk;
        partial void OnCC3ShedLengthOkChanging(Nullable<global::System.Int32> value);
        partial void OnCC3ShedLengthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC3SlabsRFT
        {
            get
            {
                return _CC3SlabsRFT;
            }
            set
            {
                OnCC3SlabsRFTChanging(value);
                ReportPropertyChanging("CC3SlabsRFT");
                _CC3SlabsRFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3SlabsRFT");
                OnCC3SlabsRFTChanged();
            }
        }
        private Nullable<global::System.Int32> _CC3SlabsRFT;
        partial void OnCC3SlabsRFTChanging(Nullable<global::System.Int32> value);
        partial void OnCC3SlabsRFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CC3SlabsAppliedTGrade
        {
            get
            {
                return _CC3SlabsAppliedTGrade;
            }
            set
            {
                OnCC3SlabsAppliedTGradeChanging(value);
                ReportPropertyChanging("CC3SlabsAppliedTGrade");
                _CC3SlabsAppliedTGrade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3SlabsAppliedTGrade");
                OnCC3SlabsAppliedTGradeChanged();
            }
        }
        private Nullable<global::System.Int32> _CC3SlabsAppliedTGrade;
        partial void OnCC3SlabsAppliedTGradeChanging(Nullable<global::System.Int32> value);
        partial void OnCC3SlabsAppliedTGradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC3TonnesMade
        {
            get
            {
                return _CC3TonnesMade;
            }
            set
            {
                OnCC3TonnesMadeChanging(value);
                ReportPropertyChanging("CC3TonnesMade");
                _CC3TonnesMade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3TonnesMade");
                OnCC3TonnesMadeChanged();
            }
        }
        private Nullable<global::System.Single> _CC3TonnesMade;
        partial void OnCC3TonnesMadeChanging(Nullable<global::System.Single> value);
        partial void OnCC3TonnesMadeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC3TonnesMadeSchedule
        {
            get
            {
                return _CC3TonnesMadeSchedule;
            }
            set
            {
                OnCC3TonnesMadeScheduleChanging(value);
                ReportPropertyChanging("CC3TonnesMadeSchedule");
                _CC3TonnesMadeSchedule = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3TonnesMadeSchedule");
                OnCC3TonnesMadeScheduleChanged();
            }
        }
        private Nullable<global::System.Single> _CC3TonnesMadeSchedule;
        partial void OnCC3TonnesMadeScheduleChanging(Nullable<global::System.Single> value);
        partial void OnCC3TonnesMadeScheduleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC3TonnesGradeOk
        {
            get
            {
                return _CC3TonnesGradeOk;
            }
            set
            {
                OnCC3TonnesGradeOkChanging(value);
                ReportPropertyChanging("CC3TonnesGradeOk");
                _CC3TonnesGradeOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3TonnesGradeOk");
                OnCC3TonnesGradeOkChanged();
            }
        }
        private Nullable<global::System.Single> _CC3TonnesGradeOk;
        partial void OnCC3TonnesGradeOkChanging(Nullable<global::System.Single> value);
        partial void OnCC3TonnesGradeOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC3TonnesWidthOk
        {
            get
            {
                return _CC3TonnesWidthOk;
            }
            set
            {
                OnCC3TonnesWidthOkChanging(value);
                ReportPropertyChanging("CC3TonnesWidthOk");
                _CC3TonnesWidthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3TonnesWidthOk");
                OnCC3TonnesWidthOkChanged();
            }
        }
        private Nullable<global::System.Single> _CC3TonnesWidthOk;
        partial void OnCC3TonnesWidthOkChanging(Nullable<global::System.Single> value);
        partial void OnCC3TonnesWidthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC3TonnesLengthOk
        {
            get
            {
                return _CC3TonnesLengthOk;
            }
            set
            {
                OnCC3TonnesLengthOkChanging(value);
                ReportPropertyChanging("CC3TonnesLengthOk");
                _CC3TonnesLengthOk = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3TonnesLengthOk");
                OnCC3TonnesLengthOkChanged();
            }
        }
        private Nullable<global::System.Single> _CC3TonnesLengthOk;
        partial void OnCC3TonnesLengthOkChanging(Nullable<global::System.Single> value);
        partial void OnCC3TonnesLengthOkChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC3TonnesRFT
        {
            get
            {
                return _CC3TonnesRFT;
            }
            set
            {
                OnCC3TonnesRFTChanging(value);
                ReportPropertyChanging("CC3TonnesRFT");
                _CC3TonnesRFT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3TonnesRFT");
                OnCC3TonnesRFTChanged();
            }
        }
        private Nullable<global::System.Single> _CC3TonnesRFT;
        partial void OnCC3TonnesRFTChanging(Nullable<global::System.Single> value);
        partial void OnCC3TonnesRFTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CC3TonnesAppliedTGrade
        {
            get
            {
                return _CC3TonnesAppliedTGrade;
            }
            set
            {
                OnCC3TonnesAppliedTGradeChanging(value);
                ReportPropertyChanging("CC3TonnesAppliedTGrade");
                _CC3TonnesAppliedTGrade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CC3TonnesAppliedTGrade");
                OnCC3TonnesAppliedTGradeChanged();
            }
        }
        private Nullable<global::System.Single> _CC3TonnesAppliedTGrade;
        partial void OnCC3TonnesAppliedTGradeChanging(Nullable<global::System.Single> value);
        partial void OnCC3TonnesAppliedTGradeChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OasisSchema", Name="SlabStock")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SlabStock : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SlabStock object.
        /// </summary>
        /// <param name="sSIndex">Initial value of the SSIndex property.</param>
        public static SlabStock CreateSlabStock(global::System.Int32 sSIndex)
        {
            SlabStock slabStock = new SlabStock();
            slabStock.SSIndex = sSIndex;
            return slabStock;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SSIndex
        {
            get
            {
                return _SSIndex;
            }
            set
            {
                if (_SSIndex != value)
                {
                    OnSSIndexChanging(value);
                    ReportPropertyChanging("SSIndex");
                    _SSIndex = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SSIndex");
                    OnSSIndexChanged();
                }
            }
        }
        private global::System.Int32 _SSIndex;
        partial void OnSSIndexChanging(global::System.Int32 value);
        partial void OnSSIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SSDate
        {
            get
            {
                return _SSDate;
            }
            set
            {
                OnSSDateChanging(value);
                ReportPropertyChanging("SSDate");
                _SSDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SSDate");
                OnSSDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _SSDate;
        partial void OnSSDateChanging(Nullable<global::System.DateTime> value);
        partial void OnSSDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LSTD
        {
            get
            {
                return _LSTD;
            }
            set
            {
                OnLSTDChanging(value);
                ReportPropertyChanging("LSTD");
                _LSTD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LSTD");
                OnLSTDChanged();
            }
        }
        private global::System.String _LSTD;
        partial void OnLSTDChanging(global::System.String value);
        partial void OnLSTDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LSTT
        {
            get
            {
                return _LSTT;
            }
            set
            {
                OnLSTTChanging(value);
                ReportPropertyChanging("LSTT");
                _LSTT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LSTT");
                OnLSTTChanged();
            }
        }
        private global::System.String _LSTT;
        partial void OnLSTTChanging(global::System.String value);
        partial void OnLSTTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> SLAB_STOCK
        {
            get
            {
                return _SLAB_STOCK;
            }
            set
            {
                OnSLAB_STOCKChanging(value);
                ReportPropertyChanging("SLAB_STOCK");
                _SLAB_STOCK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SLAB_STOCK");
                OnSLAB_STOCKChanged();
            }
        }
        private Nullable<global::System.Single> _SLAB_STOCK;
        partial void OnSLAB_STOCKChanging(Nullable<global::System.Single> value);
        partial void OnSLAB_STOCKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> PT_STOCK
        {
            get
            {
                return _PT_STOCK;
            }
            set
            {
                OnPT_STOCKChanging(value);
                ReportPropertyChanging("PT_STOCK");
                _PT_STOCK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PT_STOCK");
                OnPT_STOCKChanged();
            }
        }
        private Nullable<global::System.Single> _PT_STOCK;
        partial void OnPT_STOCKChanging(Nullable<global::System.Single> value);
        partial void OnPT_STOCKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> LL_STOCK
        {
            get
            {
                return _LL_STOCK;
            }
            set
            {
                OnLL_STOCKChanging(value);
                ReportPropertyChanging("LL_STOCK");
                _LL_STOCK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LL_STOCK");
                OnLL_STOCKChanged();
            }
        }
        private Nullable<global::System.Single> _LL_STOCK;
        partial void OnLL_STOCKChanging(Nullable<global::System.Single> value);
        partial void OnLL_STOCKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> IW_STOCK
        {
            get
            {
                return _IW_STOCK;
            }
            set
            {
                OnIW_STOCKChanging(value);
                ReportPropertyChanging("IW_STOCK");
                _IW_STOCK = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IW_STOCK");
                OnIW_STOCKChanged();
            }
        }
        private Nullable<global::System.Single> _IW_STOCK;
        partial void OnIW_STOCKChanging(Nullable<global::System.Single> value);
        partial void OnIW_STOCKChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> FREETOROLL
        {
            get
            {
                return _FREETOROLL;
            }
            set
            {
                OnFREETOROLLChanging(value);
                ReportPropertyChanging("FREETOROLL");
                _FREETOROLL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FREETOROLL");
                OnFREETOROLLChanged();
            }
        }
        private Nullable<global::System.Single> _FREETOROLL;
        partial void OnFREETOROLLChanging(Nullable<global::System.Single> value);
        partial void OnFREETOROLLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> PROCESSING
        {
            get
            {
                return _PROCESSING;
            }
            set
            {
                OnPROCESSINGChanging(value);
                ReportPropertyChanging("PROCESSING");
                _PROCESSING = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PROCESSING");
                OnPROCESSINGChanged();
            }
        }
        private Nullable<global::System.Single> _PROCESSING;
        partial void OnPROCESSINGChanging(Nullable<global::System.Single> value);
        partial void OnPROCESSINGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> HELD
        {
            get
            {
                return _HELD;
            }
            set
            {
                OnHELDChanging(value);
                ReportPropertyChanging("HELD");
                _HELD = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HELD");
                OnHELDChanged();
            }
        }
        private Nullable<global::System.Single> _HELD;
        partial void OnHELDChanging(Nullable<global::System.Single> value);
        partial void OnHELDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> APPLIED
        {
            get
            {
                return _APPLIED;
            }
            set
            {
                OnAPPLIEDChanging(value);
                ReportPropertyChanging("APPLIED");
                _APPLIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("APPLIED");
                OnAPPLIEDChanged();
            }
        }
        private Nullable<global::System.Single> _APPLIED;
        partial void OnAPPLIEDChanging(Nullable<global::System.Single> value);
        partial void OnAPPLIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> APPLIED_PT
        {
            get
            {
                return _APPLIED_PT;
            }
            set
            {
                OnAPPLIED_PTChanging(value);
                ReportPropertyChanging("APPLIED_PT");
                _APPLIED_PT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("APPLIED_PT");
                OnAPPLIED_PTChanged();
            }
        }
        private Nullable<global::System.Single> _APPLIED_PT;
        partial void OnAPPLIED_PTChanging(Nullable<global::System.Single> value);
        partial void OnAPPLIED_PTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> APPLIED_LL
        {
            get
            {
                return _APPLIED_LL;
            }
            set
            {
                OnAPPLIED_LLChanging(value);
                ReportPropertyChanging("APPLIED_LL");
                _APPLIED_LL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("APPLIED_LL");
                OnAPPLIED_LLChanged();
            }
        }
        private Nullable<global::System.Single> _APPLIED_LL;
        partial void OnAPPLIED_LLChanging(Nullable<global::System.Single> value);
        partial void OnAPPLIED_LLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> UNAPPLIED
        {
            get
            {
                return _UNAPPLIED;
            }
            set
            {
                OnUNAPPLIEDChanging(value);
                ReportPropertyChanging("UNAPPLIED");
                _UNAPPLIED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UNAPPLIED");
                OnUNAPPLIEDChanged();
            }
        }
        private Nullable<global::System.Single> _UNAPPLIED;
        partial void OnUNAPPLIEDChanging(Nullable<global::System.Single> value);
        partial void OnUNAPPLIEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> UNAPPLIED_PT
        {
            get
            {
                return _UNAPPLIED_PT;
            }
            set
            {
                OnUNAPPLIED_PTChanging(value);
                ReportPropertyChanging("UNAPPLIED_PT");
                _UNAPPLIED_PT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UNAPPLIED_PT");
                OnUNAPPLIED_PTChanged();
            }
        }
        private Nullable<global::System.Single> _UNAPPLIED_PT;
        partial void OnUNAPPLIED_PTChanging(Nullable<global::System.Single> value);
        partial void OnUNAPPLIED_PTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> UNAPPLIED_LL
        {
            get
            {
                return _UNAPPLIED_LL;
            }
            set
            {
                OnUNAPPLIED_LLChanging(value);
                ReportPropertyChanging("UNAPPLIED_LL");
                _UNAPPLIED_LL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UNAPPLIED_LL");
                OnUNAPPLIED_LLChanged();
            }
        }
        private Nullable<global::System.Single> _UNAPPLIED_LL;
        partial void OnUNAPPLIED_LLChanging(Nullable<global::System.Single> value);
        partial void OnUNAPPLIED_LLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> CONCESSION
        {
            get
            {
                return _CONCESSION;
            }
            set
            {
                OnCONCESSIONChanging(value);
                ReportPropertyChanging("CONCESSION");
                _CONCESSION = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CONCESSION");
                OnCONCESSIONChanged();
            }
        }
        private Nullable<global::System.Single> _CONCESSION;
        partial void OnCONCESSIONChanging(Nullable<global::System.Single> value);
        partial void OnCONCESSIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> TAPERED
        {
            get
            {
                return _TAPERED;
            }
            set
            {
                OnTAPEREDChanging(value);
                ReportPropertyChanging("TAPERED");
                _TAPERED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TAPERED");
                OnTAPEREDChanged();
            }
        }
        private Nullable<global::System.Single> _TAPERED;
        partial void OnTAPEREDChanging(Nullable<global::System.Single> value);
        partial void OnTAPEREDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> ONSCHED
        {
            get
            {
                return _ONSCHED;
            }
            set
            {
                OnONSCHEDChanging(value);
                ReportPropertyChanging("ONSCHED");
                _ONSCHED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ONSCHED");
                OnONSCHEDChanged();
            }
        }
        private Nullable<global::System.Single> _ONSCHED;
        partial void OnONSCHEDChanging(Nullable<global::System.Single> value);
        partial void OnONSCHEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> GRIDDED
        {
            get
            {
                return _GRIDDED;
            }
            set
            {
                OnGRIDDEDChanging(value);
                ReportPropertyChanging("GRIDDED");
                _GRIDDED = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("GRIDDED");
                OnGRIDDEDChanged();
            }
        }
        private Nullable<global::System.Single> _GRIDDED;
        partial void OnGRIDDEDChanging(Nullable<global::System.Single> value);
        partial void OnGRIDDEDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> AVE_DWELL
        {
            get
            {
                return _AVE_DWELL;
            }
            set
            {
                OnAVE_DWELLChanging(value);
                ReportPropertyChanging("AVE_DWELL");
                _AVE_DWELL = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AVE_DWELL");
                OnAVE_DWELLChanged();
            }
        }
        private Nullable<global::System.Single> _AVE_DWELL;
        partial void OnAVE_DWELLChanging(Nullable<global::System.Single> value);
        partial void OnAVE_DWELLChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> AVE_EVENTS
        {
            get
            {
                return _AVE_EVENTS;
            }
            set
            {
                OnAVE_EVENTSChanging(value);
                ReportPropertyChanging("AVE_EVENTS");
                _AVE_EVENTS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AVE_EVENTS");
                OnAVE_EVENTSChanged();
            }
        }
        private Nullable<global::System.Single> _AVE_EVENTS;
        partial void OnAVE_EVENTSChanging(Nullable<global::System.Single> value);
        partial void OnAVE_EVENTSChanged();

        #endregion

    
    }

    #endregion

    
}
