// <autogenerated />

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Steel & Slab Heat Information System")]
[assembly: AssemblyDescription("Steel & Slab Heat Information System for Port Talbot Steel Works, UK. Created by the Process Control Services Department.")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Tata Steel UK")]
[assembly: AssemblyProduct("Elvis Port Talbot")]
[assembly: AssemblyCopyright("Copyright © Tata Steel ")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("6e82171b-f7da-448d-a037-86416feb9ef0")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
[assembly: AssemblyVersion("5.2.0.9")]
[assembly: AssemblyFileVersion("5.2.0.9")]
