//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elvis.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainFormLocation {
            get {
                return ((global::System.Drawing.Point)(this["MainFormLocation"]));
            }
            set {
                this["MainFormLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("94, 255, 252")]
        public global::System.Drawing.Color ColourCaster1 {
            get {
                return ((global::System.Drawing.Color)(this["ColourCaster1"]));
            }
            set {
                this["ColourCaster1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("191, 255, 254")]
        public global::System.Drawing.Color ColourCaster1Plan {
            get {
                return ((global::System.Drawing.Color)(this["ColourCaster1Plan"]));
            }
            set {
                this["ColourCaster1Plan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 71, 234")]
        public global::System.Drawing.Color ColourCaster2 {
            get {
                return ((global::System.Drawing.Color)(this["ColourCaster2"]));
            }
            set {
                this["ColourCaster2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 184, 247")]
        public global::System.Drawing.Color ColourCaster2Plan {
            get {
                return ((global::System.Drawing.Color)(this["ColourCaster2Plan"]));
            }
            set {
                this["ColourCaster2Plan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("249, 255, 69")]
        public global::System.Drawing.Color ColourCaster3 {
            get {
                return ((global::System.Drawing.Color)(this["ColourCaster3"]));
            }
            set {
                this["ColourCaster3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("253, 255, 196")]
        public global::System.Drawing.Color ColourCaster3Plan {
            get {
                return ((global::System.Drawing.Color)(this["ColourCaster3Plan"]));
            }
            set {
                this["ColourCaster3Plan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18, 46, 255")]
        public global::System.Drawing.Color ColourVessel1 {
            get {
                return ((global::System.Drawing.Color)(this["ColourVessel1"]));
            }
            set {
                this["ColourVessel1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("138, 151, 255")]
        public global::System.Drawing.Color ColourVessel1Plan {
            get {
                return ((global::System.Drawing.Color)(this["ColourVessel1Plan"]));
            }
            set {
                this["ColourVessel1Plan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 157, 0")]
        public global::System.Drawing.Color ColourVessel2 {
            get {
                return ((global::System.Drawing.Color)(this["ColourVessel2"]));
            }
            set {
                this["ColourVessel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 211, 140")]
        public global::System.Drawing.Color ColourVessel2Plan {
            get {
                return ((global::System.Drawing.Color)(this["ColourVessel2Plan"]));
            }
            set {
                this["ColourVessel2Plan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("214, 219, 255")]
        public global::System.Drawing.Color ColourHeatScheduler1 {
            get {
                return ((global::System.Drawing.Color)(this["ColourHeatScheduler1"]));
            }
            set {
                this["ColourHeatScheduler1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 255, 207")]
        public global::System.Drawing.Color ColourHeatScheduler2 {
            get {
                return ((global::System.Drawing.Color)(this["ColourHeatScheduler2"]));
            }
            set {
                this["ColourHeatScheduler2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string TableTheme {
            get {
                return ((string)(this["TableTheme"]));
            }
            set {
                this["TableTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlLight")]
        public global::System.Drawing.Color ColourBackground {
            get {
                return ((global::System.Drawing.Color)(this["ColourBackground"]));
            }
            set {
                this["ColourBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlText")]
        public global::System.Drawing.Color ColourText {
            get {
                return ((global::System.Drawing.Color)(this["ColourText"]));
            }
            set {
                this["ColourText"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan RefreshRate {
            get {
                return ((global::System.TimeSpan)(this["RefreshRate"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColourHighlight {
            get {
                return ((global::System.Drawing.Color)(this["ColourHighlight"]));
            }
            set {
                this["ColourHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color TibExternal {
            get {
                return ((global::System.Drawing.Color)(this["TibExternal"]));
            }
            set {
                this["TibExternal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BlueViolet")]
        public global::System.Drawing.Color TibMultiServ {
            get {
                return ((global::System.Drawing.Color)(this["TibMultiServ"]));
            }
            set {
                this["TibMultiServ"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gold")]
        public global::System.Drawing.Color TibHMScrap {
            get {
                return ((global::System.Drawing.Color)(this["TibHMScrap"]));
            }
            set {
                this["TibHMScrap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SeaGreen")]
        public global::System.Drawing.Color TibVessels {
            get {
                return ((global::System.Drawing.Color)(this["TibVessels"]));
            }
            set {
                this["TibVessels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HotPink")]
        public global::System.Drawing.Color TibPlan {
            get {
                return ((global::System.Drawing.Color)(this["TibPlan"]));
            }
            set {
                this["TibPlan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YellowGreen")]
        public global::System.Drawing.Color TibSecSteel {
            get {
                return ((global::System.Drawing.Color)(this["TibSecSteel"]));
            }
            set {
                this["TibSecSteel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SkyBlue")]
        public global::System.Drawing.Color TibCasters {
            get {
                return ((global::System.Drawing.Color)(this["TibCasters"]));
            }
            set {
                this["TibCasters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Peru")]
        public global::System.Drawing.Color TibCranes {
            get {
                return ((global::System.Drawing.Color)(this["TibCranes"]));
            }
            set {
                this["TibCranes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DarkGray")]
        public global::System.Drawing.Color TibNoReason {
            get {
                return ((global::System.Drawing.Color)(this["TibNoReason"]));
            }
            set {
                this["TibNoReason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TibExternalText {
            get {
                return ((global::System.Drawing.Color)(this["TibExternalText"]));
            }
            set {
                this["TibExternalText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TibMultiServText {
            get {
                return ((global::System.Drawing.Color)(this["TibMultiServText"]));
            }
            set {
                this["TibMultiServText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TibHMScrapText {
            get {
                return ((global::System.Drawing.Color)(this["TibHMScrapText"]));
            }
            set {
                this["TibHMScrapText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TibVesselsText {
            get {
                return ((global::System.Drawing.Color)(this["TibVesselsText"]));
            }
            set {
                this["TibVesselsText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TibPlanText {
            get {
                return ((global::System.Drawing.Color)(this["TibPlanText"]));
            }
            set {
                this["TibPlanText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TibSecSteelText {
            get {
                return ((global::System.Drawing.Color)(this["TibSecSteelText"]));
            }
            set {
                this["TibSecSteelText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TibCastersText {
            get {
                return ((global::System.Drawing.Color)(this["TibCastersText"]));
            }
            set {
                this["TibCastersText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TibCranesText {
            get {
                return ((global::System.Drawing.Color)(this["TibCranesText"]));
            }
            set {
                this["TibCranesText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TibNoReasonText {
            get {
                return ((global::System.Drawing.Color)(this["TibNoReasonText"]));
            }
            set {
                this["TibNoReasonText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int HeightTibNotProducing {
            get {
                return ((int)(this["HeightTibNotProducing"]));
            }
            set {
                this["HeightTibNotProducing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int HeightTibProducing {
            get {
                return ((int)(this["HeightTibProducing"]));
            }
            set {
                this["HeightTibProducing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18")]
        public int HeightTibInProcess {
            get {
                return ((int)(this["HeightTibInProcess"]));
            }
            set {
                this["HeightTibInProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int HeightTibOutProcess {
            get {
                return ((int)(this["HeightTibOutProcess"]));
            }
            set {
                this["HeightTibOutProcess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int HeightTibUnproductive {
            get {
                return ((int)(this["HeightTibUnproductive"]));
            }
            set {
                this["HeightTibUnproductive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuickTibShadows {
            get {
                return ((bool)(this["QuickTibShadows"]));
            }
            set {
                this["QuickTibShadows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickTibTimeLine {
            get {
                return ((bool)(this["QuickTibTimeLine"]));
            }
            set {
                this["QuickTibTimeLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickTibLegend {
            get {
                return ((bool)(this["QuickTibLegend"]));
            }
            set {
                this["QuickTibLegend"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("65")]
        public int QuickTibCellWidth {
            get {
                return ((int)(this["QuickTibCellWidth"]));
            }
            set {
                this["QuickTibCellWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickHeatShadows {
            get {
                return ((bool)(this["QuickHeatShadows"]));
            }
            set {
                this["QuickHeatShadows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickHeatTimeLine {
            get {
                return ((bool)(this["QuickHeatTimeLine"]));
            }
            set {
                this["QuickHeatTimeLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int QuickHeatCellWidth {
            get {
                return ((int)(this["QuickHeatCellWidth"]));
            }
            set {
                this["QuickHeatCellWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Caster")]
        public string QuickHeatColourBy {
            get {
                return ((string)(this["QuickHeatColourBy"]));
            }
            set {
                this["QuickHeatColourBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string QuickHeatExtraData {
            get {
                return ((string)(this["QuickHeatExtraData"]));
            }
            set {
                this["QuickHeatExtraData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickCasterShadows {
            get {
                return ((bool)(this["QuickCasterShadows"]));
            }
            set {
                this["QuickCasterShadows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickCasterTimeLine {
            get {
                return ((bool)(this["QuickCasterTimeLine"]));
            }
            set {
                this["QuickCasterTimeLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool QuickCasterChart {
            get {
                return ((bool)(this["QuickCasterChart"]));
            }
            set {
                this["QuickCasterChart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuickCaster7pmPlan {
            get {
                return ((bool)(this["QuickCaster7pmPlan"]));
            }
            set {
                this["QuickCaster7pmPlan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string QuickCasterExtraData {
            get {
                return ((string)(this["QuickCasterExtraData"]));
            }
            set {
                this["QuickCasterExtraData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuickCaster7amStock {
            get {
                return ((bool)(this["QuickCaster7amStock"]));
            }
            set {
                this["QuickCaster7amStock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 8.25pt")]
        public global::System.Drawing.Font FontOverviewHeatNo {
            get {
                return ((global::System.Drawing.Font)(this["FontOverviewHeatNo"]));
            }
            set {
                this["FontOverviewHeatNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 8.25pt")]
        public global::System.Drawing.Font FontOverviewExtraData {
            get {
                return ((global::System.Drawing.Font)(this["FontOverviewExtraData"]));
            }
            set {
                this["FontOverviewExtraData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 8.25pt")]
        public global::System.Drawing.Font FontTibHeatNo {
            get {
                return ((global::System.Drawing.Font)(this["FontTibHeatNo"]));
            }
            set {
                this["FontTibHeatNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 8.25pt")]
        public global::System.Drawing.Font FontCasterHeatNo {
            get {
                return ((global::System.Drawing.Font)(this["FontCasterHeatNo"]));
            }
            set {
                this["FontCasterHeatNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 8.25pt")]
        public global::System.Drawing.Font FontCasterExtraData {
            get {
                return ((global::System.Drawing.Font)(this["FontCasterExtraData"]));
            }
            set {
                this["FontCasterExtraData"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoUpdate {
            get {
                return ((bool)(this["AutoUpdate"]));
            }
            set {
                this["AutoUpdate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TibUnitsToHide {
            get {
                return ((string)(this["TibUnitsToHide"]));
            }
            set {
                this["TibUnitsToHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HeatUnitsToHide {
            get {
                return ((string)(this["HeatUnitsToHide"]));
            }
            set {
                this["HeatUnitsToHide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TibReportFilters {
            get {
                return ((string)(this["TibReportFilters"]));
            }
            set {
                this["TibReportFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DelayAnalysisReportFilters {
            get {
                return ((string)(this["DelayAnalysisReportFilters"]));
            }
            set {
                this["DelayAnalysisReportFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DelayAnalysisReportGroupBy {
            get {
                return ((string)(this["DelayAnalysisReportGroupBy"]));
            }
            set {
                this["DelayAnalysisReportGroupBy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color SlowCastColour {
            get {
                return ((global::System.Drawing.Color)(this["SlowCastColour"]));
            }
            set {
                this["SlowCastColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color LimePlantEventColour {
            get {
                return ((global::System.Drawing.Color)(this["LimePlantEventColour"]));
            }
            set {
                this["LimePlantEventColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HotPink")]
        public global::System.Drawing.Color LimePlantChangeOverColour {
            get {
                return ((global::System.Drawing.Color)(this["LimePlantChangeOverColour"]));
            }
            set {
                this["LimePlantChangeOverColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Courier New, 8.25pt")]
        public global::System.Drawing.Font FontOverviewMiscast {
            get {
                return ((global::System.Drawing.Font)(this["FontOverviewMiscast"]));
            }
            set {
                this["FontOverviewMiscast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTargetCastingRateLine {
            get {
                return ((bool)(this["ShowTargetCastingRateLine"]));
            }
            set {
                this["ShowTargetCastingRateLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowTonnesPerHourHMGridline {
            get {
                return ((bool)(this["ShowTonnesPerHourHMGridline"]));
            }
            set {
                this["ShowTonnesPerHourHMGridline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTonnesPerMinuteHMGridline {
            get {
                return ((bool)(this["ShowTonnesPerMinuteHMGridline"]));
            }
            set {
                this["ShowTonnesPerMinuteHMGridline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuickHeatMiscasts {
            get {
                return ((bool)(this["QuickHeatMiscasts"]));
            }
            set {
                this["QuickHeatMiscasts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHMBufferLines {
            get {
                return ((bool)(this["ShowHMBufferLines"]));
            }
            set {
                this["ShowHMBufferLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCastingRateLines {
            get {
                return ((bool)(this["ShowCastingRateLines"]));
            }
            set {
                this["ShowCastingRateLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string CBMColourScheme {
            get {
                return ((string)(this["CBMColourScheme"]));
            }
            set {
                this["CBMColourScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("128, 128, 255")]
        public global::System.Drawing.Color OEELevel1Background {
            get {
                return ((global::System.Drawing.Color)(this["OEELevel1Background"]));
            }
            set {
                this["OEELevel1Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Azure")]
        public global::System.Drawing.Color OEELevel2Background {
            get {
                return ((global::System.Drawing.Color)(this["OEELevel2Background"]));
            }
            set {
                this["OEELevel2Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color OEEL1Text {
            get {
                return ((global::System.Drawing.Color)(this["OEEL1Text"]));
            }
            set {
                this["OEEL1Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color OEEL2Text {
            get {
                return ((global::System.Drawing.Color)(this["OEEL2Text"]));
            }
            set {
                this["OEEL2Text"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSelectors {
            get {
                return ((bool)(this["ShowSelectors"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string EBMColourScheme {
            get {
                return ((string)(this["EBMColourScheme"]));
            }
            set {
                this["EBMColourScheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int OverviewDaysToShow {
            get {
                return ((int)(this["OverviewDaysToShow"]));
            }
            set {
                this["OverviewDaysToShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int TibDaysToShow {
            get {
                return ((int)(this["TibDaysToShow"]));
            }
            set {
                this["TibDaysToShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int MemoryLimit {
            get {
                return ((int)(this["MemoryLimit"]));
            }
            set {
                this["MemoryLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuickCaster10amPlan {
            get {
                return ((bool)(this["QuickCaster10amPlan"]));
            }
            set {
                this["QuickCaster10amPlan"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int MinHeatNumber {
            get {
                return ((int)(this["MinHeatNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("89999")]
        public int MaxHeatNumber {
            get {
                return ((int)(this["MaxHeatNumber"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20, 200, 250")]
        public global::System.Drawing.Color ColourHighlight1 {
            get {
                return ((global::System.Drawing.Color)(this["ColourHighlight1"]));
            }
            set {
                this["ColourHighlight1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("244, 60, 60")]
        public global::System.Drawing.Color ColourHighlight2 {
            get {
                return ((global::System.Drawing.Color)(this["ColourHighlight2"]));
            }
            set {
                this["ColourHighlight2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24, 160, 24")]
        public global::System.Drawing.Color ColourHighlight3 {
            get {
                return ((global::System.Drawing.Color)(this["ColourHighlight3"]));
            }
            set {
                this["ColourHighlight3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 142, 30")]
        public global::System.Drawing.Color ColourHighlight4 {
            get {
                return ((global::System.Drawing.Color)(this["ColourHighlight4"]));
            }
            set {
                this["ColourHighlight4"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000018")]
        public int MinSlabNumber {
            get {
                return ((int)(this["MinSlabNumber"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999999")]
        public int MaxSlabNumber {
            get {
                return ((int)(this["MaxSlabNumber"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PowderBlue")]
        public global::System.Drawing.Color ColourDashHeaderBack {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashHeaderBack"]));
            }
            set {
                this["ColourDashHeaderBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WhiteSmoke")]
        public global::System.Drawing.Color ColourDashRowBack {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashRowBack"]));
            }
            set {
                this["ColourDashRowBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("218, 235, 255")]
        public global::System.Drawing.Color ColourDashAltRowBack {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashAltRowBack"]));
            }
            set {
                this["ColourDashAltRowBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38, 244, 62")]
        public global::System.Drawing.Color ColourDashGoodBack {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashGoodBack"]));
            }
            set {
                this["ColourDashGoodBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("225, 35, 1")]
        public global::System.Drawing.Color ColourDashBadBack {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashBadBack"]));
            }
            set {
                this["ColourDashBadBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColourDashMissingBack {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashMissingBack"]));
            }
            set {
                this["ColourDashMissingBack"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColourDashHeaderText {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashHeaderText"]));
            }
            set {
                this["ColourDashHeaderText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColourDashRowText {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashRowText"]));
            }
            set {
                this["ColourDashRowText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColourDashAltRowText {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashAltRowText"]));
            }
            set {
                this["ColourDashAltRowText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColourDashGoodText {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashGoodText"]));
            }
            set {
                this["ColourDashGoodText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color ColourDashBadText {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashBadText"]));
            }
            set {
                this["ColourDashBadText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ColourDashMissingText {
            get {
                return ((global::System.Drawing.Color)(this["ColourDashMissingText"]));
            }
            set {
                this["ColourDashMissingText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TrendShowLegend {
            get {
                return ((bool)(this["TrendShowLegend"]));
            }
            set {
                this["TrendShowLegend"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("21")]
        public int DashboardRowHeight {
            get {
                return ((int)(this["DashboardRowHeight"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public int DashboardSingleBoxWidth {
            get {
                return ((int)(this["DashboardSingleBoxWidth"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1, 1, 1, 1")]
        public global::System.Windows.Forms.Padding DashboardBoxPadding {
            get {
                return ((global::System.Windows.Forms.Padding)(this["DashboardBoxPadding"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif, 8.25pt")]
        public global::System.Drawing.Font DashboardBoxFont {
            get {
                return ((global::System.Drawing.Font)(this["DashboardBoxFont"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\pt-fs1.porttalbot.pcswales.corusgroup.com\\ELVISDRF")]
        public string DRFFolderForAttachment {
            get {
                return ((string)(this["DRFFolderForAttachment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("elvisdrf")]
        public string DRFFileOperationUserUserName {
            get {
                return ((string)(this["DRFFileOperationUserUserName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M@nchester")]
        public string DRFFileOperationUserPassword {
            get {
                return ((string)(this["DRFFileOperationUserPassword"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("bspt_proc_ctrl")]
        public string DRFFileOperationDomain {
            get {
                return ((string)(this["DRFFileOperationDomain"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50000000")]
        public long DRFFileMaxSize {
            get {
                return ((long)(this["DRFFileMaxSize"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\1.61.67.198\\plant data\\PT HMDeS IR Data\\SkimImages\\")]
        public string HMSkimImageLocation {
            get {
                return ((string)(this["HMSkimImageLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ptwide.porttalbot.pcswales.corusgroup.com/RotaService/api/Rota/")]
        public string RotaService {
            get {
                return ((string)(this["RotaService"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-30")]
        public int CMCMaxDaysHistory {
            get {
                return ((int)(this["CMCMaxDaysHistory"]));
            }
            set {
                this["CMCMaxDaysHistory"] = value;
            }
        }
    }
}
